require "json"
require "./base/model"

module PlaceOS::Model
  class ChatMessage < ModelWithAutoKey
    enum Role
      # Can be generated by the end users of an application, or set by a developer as an instruction.
      User
      # The system message helps set the behavior of the assistant.
      # GPT 3 does not always pay strong attention to system messages
      System
      # The assistant messages help store prior responses. They can also be written by a developer to help give examples of desired behavior.
      Assistant
      # function
      Function

      def to_s : String
        super.downcase
      end
    end

    table :chat_messages

    attribute chat_id : String
    attribute role : Role = Role::User, converter: Enum::ValueConverter(PlaceOS::Model::ChatMessage::Role), es_type: "integer"
    attribute content : String? = nil
    attribute tokens : Int32 = 0

    # When `role` is `Function`, then this should contain the name of the function whose response is in the `content`.
    attribute function_name : String? = nil
    attribute function_args : JSON::Any? = nil
    attribute tool_call_id : String? = nil

    belongs_to Chat
  end
end
