require "uuid"
require "uuid/json"

require "./base/model"
require "./partner"

module PlaceOS::Model
  # A customer organisation (e.g. UCLA, Acadian) — the estate owner in the
  # PPT-526 hierarchy: Partner -> Client -> Authority (domain) -> ...
  #
  # `partner_id` NULL means client-owned: the customer signed up and manages
  # itself without an integrator. `payer` records who receives invoices for
  # this client: the partner (integrator pays us and re-bills — the default
  # channel model) or the client directly. A client without a partner can
  # only pay for itself; `normalize_payer` keeps that invariant ahead of the
  # DB CHECK constraint.
  class Client < ::PgORM::Base
    include PgORM::Timestamps

    table :clients

    PAYER_PARTNER = "partner"
    PAYER_CLIENT  = "client"
    PAYERS        = [PAYER_PARTNER, PAYER_CLIENT]

    default_primary_key id : UUID, autogenerated: true

    attribute name : String, sanitize: :text
    attribute description : String = "", sanitize: :common
    attribute payer : String = PAYER_PARTNER, mass_assignment: false
    attribute config : Hash(String, JSON::Any) = {} of String => JSON::Any

    attribute partner_id : UUID?
    belongs_to :partner, class_name: Partner, foreign_key: partner_id

    before_save :normalize_payer

    validates :name, presence: true

    validate ->(this : Client) {
      unless PAYERS.includes?(this.payer)
        this.validation_error(:payer, "must be one of #{PAYERS.join(", ")}")
      end
    }

    validate ->(this : Client) {
      # Friendlier error ahead of the DB's partial unique indexes: names are
      # unique within a partner's book, and unique among client-owned clients.
      name = this.name
      return if name.nil? || name.empty?
      existing = Client.where(partner_id: this.partner_id, name: name).first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id
      this.validation_error(:name, "a client with this name already exists")
    }

    protected def normalize_payer
      self.payer = PAYER_CLIENT if self.partner_id.nil?
    end

    # True when the customer manages itself without an integrator.
    def client_owned? : Bool
      self.partner_id.nil?
    end

    # Domains (authorities) owned by this client.
    def authorities
      Authority.where(client_id: self.id)
    end
  end
end
