require "json"
require "time"

require "random/secure"
require "./base/model"
require "digest/md5"

module PlaceOS::Model
  class DoorkeeperApplication < PgORM::Base
    include Neuroplastic
    include OpenAPI::Generator::Serializable::Adapters::ActiveModel
    extend OpenAPI::Generator::Serializable
    include Model::Associations
    include PlaceOS::Model::Timestamps

    table :oauth_applications
    default_primary_key id : Int64?, autogenerated: true
    attribute name : String, es_subfield: "keyword"
    attribute secret : String
    attribute scopes : String = "public"
    attribute redirect_uri : String
    attribute confidential : Bool = false

    attribute uid : String, mass_assignment: false

    # Validation
    ###############################################################################################

    ensure_unique :uid

    ensure_unique :redirect_uri do |redirect_uri|
      redirect_uri.strip
    end

    ensure_unique :name do |name|
      name.strip
    end

    validates :name, presence: true
    validates :secret, presence: true
    validates :redirect_uri, presence: true

    # Callbacks
    ###############################################################################################

    before_save :generate_uid

    before_create :generate_secret

    protected def generate_uid
      check_uid = @uid
      if check_uid.nil? || check_uid.blank?
        redirect = self.redirect_uri.downcase
        if redirect.starts_with?("http")
          self.uid = Digest::MD5.hexdigest(redirect)
        else
          self.uid = Random::Secure.urlsafe_base64(25)
        end

        current_id = @id
        if current_id.nil?
          # Ensure document is treated as unpersisted
          self.new_record = true
        end
      end
    end

    protected def generate_secret
      self.secret = Random::Secure.urlsafe_base64(40)
    end
  end
end
