require "uuid"
require "uuid/json"

require "./base/model"
require "./permissions"
require "./authority"
require "./organization"
require "./partner"

module PlaceOS::Model
  # PPT-526 Stage 3: a cross-tenant authorization grant.
  #
  # Gives a user a `Permissions` bitmask over one scope — a Partner, an Organization,
  # or an Authority. Authorization resolves by walking UP from the touched
  # resource: authority -> its organization -> that organization's partner. A grant at
  # partner scope therefore covers every one of that partner's organizations, current
  # and future (the NTT-over-its-clients case); a grant at organization scope covers
  # that organization's authorities; a grant at authority scope is a single domain.
  #
  # `scope_id` is polymorphic (a Partner/Organization UUID as text, or an Authority
  # TEXT id) so it carries no FK; a grant naming a deleted scope is inert.
  class Grant < ::PgORM::Base
    include PgORM::Timestamps

    table :grants

    SCOPE_PARTNER      = "partner"
    SCOPE_ORGANIZATION = "organization"
    SCOPE_AUTHORITY    = "authority"
    SCOPE_TYPES        = [SCOPE_PARTNER, SCOPE_ORGANIZATION, SCOPE_AUTHORITY]

    default_primary_key id : UUID, autogenerated: true

    attribute user_id : String
    belongs_to :user, class_name: User, foreign_key: user_id

    attribute scope_type : String
    attribute scope_id : String

    # Stored as an Int32 bitmask. Use `permission_flags` / `permission_flags=`
    # to work with the `Permissions` flags enum directly (same shape as
    # group_users.permissions).
    attribute permissions : Int32 = 0

    # NULL = a standing grant. A non-null value in the past means expired.
    # Plain Time maps to the TIMESTAMPTZ column (same as created_at/updated_at).
    attribute expires_at : Time?

    # The user id of whoever issued this grant (audit; no FK so the trail
    # survives the grantor's deletion).
    attribute granted_by : String?

    validates :user_id, presence: true
    validates :scope_id, presence: true

    validate ->(this : Grant) {
      unless SCOPE_TYPES.includes?(this.scope_type)
        this.validation_error(:scope_type, "must be one of #{SCOPE_TYPES.join(", ")}")
      end
    }

    def permission_flags : Permissions
      Permissions.new(self.permissions)
    end

    def permission_flags=(flags : Permissions)
      self.permissions = flags.to_i
    end

    # A grant is live when it has not expired.
    def live?(at : Time = Time.utc) : Bool
      exp = self.expires_at
      exp.nil? || exp > at
    end

    # ------------------------------------------------------------------
    # Resolution
    # ------------------------------------------------------------------

    # Effective permissions a user holds over `authority`, resolved by walking
    # up authority -> organization -> partner and OR-ing every live grant on the
    # chain. Explicit grants only; the management-partner "support sees all"
    # rule is applied by the enforcement layer, not here.
    def self.resolve(user_id : String, authority : Authority, at : Time = Time.utc) : Permissions
      resolve_for_chain(user_id, scope_chain(authority), at)
    end

    # As above, addressed by authority id (returns None for an unknown id).
    def self.resolve(user_id : String, authority_id : String, at : Time = Time.utc) : Permissions
      authority = Authority.find?(authority_id)
      return Permissions::None if authority.nil?
      resolve(user_id, authority, at)
    end

    # The (scope_type, scope_id) pairs to check for a given authority, from
    # most specific to least: the authority itself, its organization, that organization's
    # partner. Missing links are simply absent.
    def self.scope_chain(authority : Authority) : Array({String, String})
      chain = [{SCOPE_AUTHORITY, authority.id.to_s}]
      if (organization_id = authority.organization_id)
        chain << {SCOPE_ORGANIZATION, organization_id.to_s}
        if (organization = Organization.find?(organization_id)) && (partner_id = organization.partner_id)
          chain << {SCOPE_PARTNER, partner_id.to_s}
        end
      end
      chain
    end

    private def self.resolve_for_chain(user_id : String, chain : Array({String, String}), at : Time) : Permissions
      return Permissions::None if chain.empty?

      # Query by the scalar user_id (a user holds few grants), then keep only
      # the live grants whose (scope_type, scope_id) is on the resource's chain
      # and OR their permissions. Filtering in memory sidesteps array binding.
      wanted = chain.to_set
      effective = Permissions::None
      Grant.where(user_id: user_id).each do |grant|
        next unless wanted.includes?({grant.scope_type, grant.scope_id})
        next unless grant.live?(at)
        effective |= grant.permission_flags
      end
      effective
    end

    # All live grants for a user (any scope).
    def self.for_user(user_id : String) : Array(Grant)
      Grant.where(user_id: user_id).select(&.live?)
    end

    # Everyone granted access to a specific scope (partner/organization admin console).
    def self.for_scope(scope_type : String, scope_id : String) : Array(Grant)
      Grant.where(scope_type: scope_type, scope_id: scope_id).to_a
    end
  end
end
