require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
# `history` defines `GroupHistory::Mixin`, which every group-subsystem
# model pulls in via `include`. It must be required before any class that
# does the include, so it goes first (before `./group/application`).
require "./group/history"
require "./group/application"

module PlaceOS::Model
  # A node in the group tree for an authority. The tree represents the
  # organisational hierarchy; applications are overlays that a group can
  # opt into (or out of) via `GroupApplicationMembership`. A single root
  # per authority is enforced by a partial unique index on
  # `(authority_id) WHERE parent_id IS NULL`.
  class Group < ::PgORM::Base
    include PgORM::Timestamps

    table :groups

    default_primary_key id : UUID, autogenerated: true

    attribute name : String
    attribute description : String = ""

    attribute authority_id : String
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    attribute parent_id : UUID?
    belongs_to :parent, class_name: Group, foreign_key: parent_id

    validates :name, presence: true
    validates :authority_id, presence: true

    validate ->(this : Group) {
      # Only validate "single root" at the model level when the parent_id
      # is NULL. The database's partial unique index is the source of truth;
      # this check short-circuits on obvious cases with a friendlier error.
      return unless this.parent_id.nil?
      existing = Group.where(authority_id: this.authority_id, parent_id: nil).first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id
      this.validation_error(:parent_id, "authority already has a root group")
    }

    validate ->(this : Group) {
      # Parent must belong to the same authority.
      parent_id = this.parent_id
      return if parent_id.nil?
      parent = Group.find?(parent_id)
      return if parent.nil?
      return if parent.authority_id == this.authority_id
      this.validation_error(:parent_id, "parent must belong to the same authority")
    }

    include GroupHistory::Mixin

    # Immediate children.
    def children
      Group.where(parent_id: self.id)
    end

    # Direct GroupUser rows for this group.
    def group_users
      GroupUser.where(group_id: self.id)
    end

    # Direct GroupZone rows for this group.
    def group_zones
      GroupZone.where(group_id: self.id)
    end

    # Application memberships for this group.
    def application_memberships
      GroupApplicationMembership.where(group_id: self.id)
    end

    # Applications this group participates in.
    def applications : Array(GroupApplication)
      ids = application_memberships.to_a.map(&.application_id)
      return [] of GroupApplication if ids.empty?
      GroupApplication.where(id: ids).to_a
    end

    # All descendant group ids (including self) via a recursive CTE.
    def descendant_ids : Array(UUID)
      ids = [] of UUID
      sql = <<-SQL
        WITH RECURSIVE descendants AS (
          SELECT id FROM groups WHERE id = $1
          UNION ALL
          SELECT g.id FROM groups g
          INNER JOIN descendants d ON g.parent_id = d.id
        )
        SELECT id FROM descendants
      SQL
      ::PgORM::Database.connection do |conn|
        conn.query(sql, self.id) do |rs|
          rs.each { ids << rs.read(UUID) }
        end
      end
      ids
    end

    # --------------------------------------------------------------------
    # GroupHistory hooks
    # --------------------------------------------------------------------

    protected def group_history_resource_type : String
      "group"
    end

    protected def group_history_resource_id : String
      self.id.to_s
    end

    protected def group_history_application_id : UUID?
      nil
    end

    protected def group_history_group_id : UUID?
      self.id
    end
  end
end

require "./group/*"
