require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
require "./permissions"
# `history` defines `GroupHistory::Mixin`, which every group-subsystem
# model pulls in via `include`. It must be required before any class that
# does the include, so it goes first.
require "./group/history"

module PlaceOS::Model
  # A node in the group tree for an authority. The tree represents the
  # organisational hierarchy. Each group declares which *subsystems*
  # (signage, events, parking, ...) it participates in via the `subsystems`
  # text array; subsystem-scoped permission queries are filtered against
  # that array. A single root per authority is enforced by a partial unique
  # index on `(authority_id) WHERE parent_id IS NULL`.
  class Group < ::PgORM::Base
    include PgORM::Timestamps

    table :groups

    default_primary_key id : UUID, autogenerated: true

    attribute name : String
    attribute description : String = ""
    attribute subsystems : Array(String) = [] of String

    attribute authority_id : String
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    attribute parent_id : UUID?
    belongs_to :parent, class_name: Group, foreign_key: parent_id

    validates :name, presence: true
    validates :authority_id, presence: true

    validate ->(this : Group) {
      # Only validate "single root" at the model level when the parent_id
      # is NULL. The database's partial unique index is the source of truth;
      # this check short-circuits on obvious cases with a friendlier error.
      return unless this.parent_id.nil?
      existing = Group.where(authority_id: this.authority_id, parent_id: nil).first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id
      this.validation_error(:parent_id, "authority already has a root group")
    }

    validate ->(this : Group) {
      # Parent must belong to the same authority.
      parent_id = this.parent_id
      return if parent_id.nil?
      parent = Group.find?(parent_id)
      return if parent.nil?
      return if parent.authority_id == this.authority_id
      this.validation_error(:parent_id, "parent must belong to the same authority")
    }

    include GroupHistory::Mixin

    # Immediate children.
    def children
      Group.where(parent_id: self.id)
    end

    # Direct GroupUser rows for this group.
    def group_users
      GroupUser.where(group_id: self.id)
    end

    # Direct GroupZone rows for this group.
    def group_zones
      GroupZone.where(group_id: self.id)
    end

    # All descendant group ids (including self) via a recursive CTE.
    def descendant_ids : Array(UUID)
      ids = [] of UUID
      sql = <<-SQL
        WITH RECURSIVE descendants AS (
          SELECT id FROM groups WHERE id = $1
          UNION ALL
          SELECT g.id FROM groups g
          INNER JOIN descendants d ON g.parent_id = d.id
        )
        SELECT id FROM descendants
      SQL
      ::PgORM::Database.connection do |conn|
        conn.query(sql, self.id) do |rs|
          rs.each { ids << rs.read(UUID) }
        end
      end
      ids
    end

    # --------------------------------------------------------------------
    # Subsystem-scoped permission query helpers
    #
    # These are the primary entry points for authorisation: callers
    # supply an `authority_id` and a `subsystem` code (e.g. "signage")
    # and the helpers compute the user's effective permissions across
    # the group/zone trees, considering only groups whose `subsystems`
    # array includes the requested subsystem.
    # --------------------------------------------------------------------

    # Zone ids this user has any non-zero effective permission on, within
    # `subsystem`. Includes zones reached transitively (via ancestor
    # group membership and via ancestor zone GroupZone rows), minus
    # anything masked off by deny rows.
    def self.accessible_zone_ids(authority_id : String, subsystem : String, user_id : String) : Array(String)
      resolve_user_permissions(authority_id, subsystem, user_id).compact_map do |zone_id, perms|
        zone_id if perms != Permissions::None
      end
    end

    # Does this user have any non-zero effective permission on this zone
    # (directly or transitively) for `subsystem`?
    def self.zone_accessible?(authority_id : String, subsystem : String, user_id : String, zone_id : String) : Bool
      effective_permissions(authority_id, subsystem, user_id, zone_id) != Permissions::None
    end

    # Effective permission bitmask for (user, zone) within `subsystem`.
    def self.effective_permissions(authority_id : String, subsystem : String, user_id : String, zone_id : String) : Permissions
      resolve_user_permissions(authority_id, subsystem, user_id)[zone_id]? || Permissions::None
    end

    # Effective permissions across a batch of zones. For every zone, the
    # closest applicable grant in that zone's own ancestry wins (replace
    # semantics — same rule as the single-zone form). Results are OR'd
    # across the list: this answers "what can the user do if *any* of
    # these zones is in play?". Zones with no applicable grant contribute
    # nothing. Returns `Permissions::None` for an empty list or for a
    # user who can't reach any of the supplied zones.
    def self.effective_permissions(authority_id : String, subsystem : String, user_id : String, zone_ids : Array(String)) : Permissions
      return Permissions::None if zone_ids.empty?
      resolved = resolve_user_permissions(authority_id, subsystem, user_id)
      zone_ids.reduce(Permissions::None) do |acc, zid|
        acc | (resolved[zid]? || Permissions::None)
      end
    end

    # Resolve the full `{zone_id => Permissions}` map for the user within
    # `subsystem`.
    #
    # Rules:
    # - User's effective perms on a group G = closest ancestor (up the group
    #   tree, inclusive) the user has an explicit GroupUser entry on
    #   (replace semantics).
    # - A GroupZone(owner, anchor) grants access starting at `anchor` and
    #   propagating down the zone tree, unless a more-specific GroupZone
    #   on the same owner exists at a descendant zone, or a `deny` row
    #   for the same owner sits on the path (masks off).
    # - Only groups whose `subsystems` array includes `subsystem`
    #   contribute grants.
    # - For each grant reaching a zone Z:
    #     - If Z == anchor: the user's perms come from `owner` itself.
    #     - If Z is a strict descendant of anchor: the user's perms come
    #       from the *deepest group in `owner`'s subtree where the user has
    #       an explicit GroupUser entry*. If no such explicit descendant
    #       exists, fall back to `owner`.
    # - Final perms at Z = OR across every contributing grant.
    private def self.resolve_user_permissions(
      authority_id : String,
      subsystem : String,
      user_id : String,
    ) : Hash(String, Permissions)
      result = {} of String => Permissions
      direct_memberships = user_direct_memberships(authority_id, user_id)
      return result if direct_memberships.empty?

      authority_groups = Group.where(authority_id: authority_id).to_a
      return result if authority_groups.empty?

      parent_of = {} of UUID => UUID
      all_group_ids = [] of UUID
      member_group_ids = [] of UUID
      authority_groups.each do |g|
        gid = g.id.not_nil!
        all_group_ids << gid
        if (parent = g.parent_id)
          parent_of[gid] = parent
        end
        member_group_ids << gid if g.subsystems.includes?(subsystem)
      end
      return result if member_group_ids.empty?

      effective_memberships = walk_up_memberships(direct_memberships, all_group_ids, parent_of)
      group_depths = compute_group_depths(all_group_ids, parent_of)
      group_descendants = compute_group_descendants(all_group_ids, parent_of)

      zone_children = zone_children_map
      rows_by_group = Hash(UUID, Array(GroupZone)).new
      GroupZone.where(group_id: member_group_ids).each do |gz|
        (rows_by_group[gz.group_id] ||= [] of GroupZone) << gz
      end

      rows_by_group.each do |owner_id, rows|
        # Which zones does *this* owner have direct rows on? Used to apply
        # replace-on-zone-tree semantics during the walk.
        by_zone = {} of String => GroupZone
        rows.each { |r| by_zone[r.zone_id] = r }

        rows.each do |row|
          grant_perms = row.deny ? Permissions::None : Permissions.new(row.permissions)
          next if grant_perms == Permissions::None

          reaching_descendant = deepest_explicit_in_subtree(
            owner_id, direct_memberships, group_descendants, group_depths,
          )
          descendant_perms = effective_memberships[reaching_descendant]?
          anchor_perms = effective_memberships[owner_id]?

          stack = [row.zone_id]
          until stack.empty?
            zone_id = stack.pop
            # Stop at any more-specific row for this owner — that row drives
            # its own subtree walk.
            next if zone_id != row.zone_id && by_zone.has_key?(zone_id)

            user_perms = zone_id == row.zone_id ? anchor_perms : descendant_perms
            if user_perms
              contribution = user_perms & grant_perms
              if contribution != Permissions::None
                result[zone_id] = (result[zone_id]? || Permissions::None) | contribution
              end
            end

            if (children = zone_children[zone_id]?)
              children.each { |c| stack << c }
            end
          end
        end
      end

      result
    end

    # User's *explicit* GroupUser rows, joined through Group to scope to
    # `authority_id`.
    private def self.user_direct_memberships(authority_id : String, user_id : String) : Hash(UUID, Permissions)
      direct = {} of UUID => Permissions
      sql = <<-SQL
        SELECT gu.group_id, gu.permissions
        FROM group_users gu
        INNER JOIN groups g ON g.id = gu.group_id
        WHERE gu.user_id = $1 AND g.authority_id = $2
      SQL
      args = [user_id.as(::PgORM::Value), authority_id.as(::PgORM::Value)]
      ::PgORM::Database.connection do |conn|
        conn.query_all(sql, args: args) do |rs|
          gid = rs.read(UUID)
          perms = rs.read(Int32)
          direct[gid] = Permissions.new(perms)
        end
      end
      direct
    end

    # Walk up the group tree from every group; each group's effective perms
    # = closest ancestor (inclusive) with an explicit entry. Groups without
    # any explicit ancestor entry are omitted.
    private def self.walk_up_memberships(
      direct : Hash(UUID, Permissions),
      all_group_ids : Array(UUID),
      parent_of : Hash(UUID, UUID),
    ) : Hash(UUID, Permissions)
      effective = {} of UUID => Permissions
      all_group_ids.each do |gid|
        current = gid
        loop do
          if (p = direct[current]?)
            effective[gid] = p
            break
          end
          next_parent = parent_of[current]?
          break if next_parent.nil?
          current = next_parent
        end
      end
      effective
    end

    private def self.compute_group_depths(
      all_group_ids : Array(UUID),
      parent_of : Hash(UUID, UUID),
    ) : Hash(UUID, Int32)
      depths = {} of UUID => Int32
      all_group_ids.each do |gid|
        depth = 0
        current = gid
        loop do
          parent = parent_of[current]?
          break if parent.nil?
          depth += 1
          current = parent
        end
        depths[gid] = depth
      end
      depths
    end

    private def self.compute_group_descendants(
      all_group_ids : Array(UUID),
      parent_of : Hash(UUID, UUID),
    ) : Hash(UUID, Array(UUID))
      children = {} of UUID => Array(UUID)
      parent_of.each do |child, parent|
        (children[parent] ||= [] of UUID) << child
      end

      descendants = {} of UUID => Array(UUID)
      all_group_ids.each do |root|
        collected = [] of UUID
        stack = [root]
        until stack.empty?
          node = stack.pop
          collected << node
          children[node]?.try &.each { |c| stack << c }
        end
        descendants[root] = collected
      end
      descendants
    end

    # Deepest group in `owner`'s subtree (inclusive) that has a direct
    # GroupUser entry for this user. Falls back to `owner` if none.
    private def self.deepest_explicit_in_subtree(
      owner : UUID,
      direct : Hash(UUID, Permissions),
      group_descendants : Hash(UUID, Array(UUID)),
      group_depths : Hash(UUID, Int32),
    ) : UUID
      candidates = group_descendants[owner]? || [owner]
      best = owner
      best_depth = group_depths[owner]? || 0
      found_explicit = direct.has_key?(owner)
      candidates.each do |gid|
        next unless direct.has_key?(gid)
        depth = group_depths[gid]? || 0
        if !found_explicit || depth > best_depth
          best = gid
          best_depth = depth
          found_explicit = true
        end
      end
      best
    end

    # Build a zone → children lookup for the full zone table. Zones are
    # typically a modest number and we need arbitrary subtree walks, so a
    # single pass here is cheaper than per-group recursive CTEs.
    private def self.zone_children_map : Hash(String, Array(String))
      children = {} of String => Array(String)
      sql = %(SELECT id, parent_id FROM "zone" WHERE parent_id IS NOT NULL)
      ::PgORM::Database.connection do |conn|
        conn.query(sql) do |rs|
          rs.each do
            id = rs.read(String)
            parent_id = rs.read(String)
            (children[parent_id] ||= [] of String) << id
          end
        end
      end
      children
    end

    # --------------------------------------------------------------------
    # GroupHistory hooks
    # --------------------------------------------------------------------

    protected def group_history_resource_type : String
      "group"
    end

    protected def group_history_resource_id : String
      self.id.to_s
    end

    protected def group_history_group_id : UUID?
      self.id
    end
  end
end

require "./group/*"
