require "uuid"
require "uuid/json"

require "./base/model"
require "./partner"

module PlaceOS::Model
  # A customer organisation (e.g. UCLA, Acadian) — the estate owner in the
  # PPT-526 hierarchy: Partner -> Organization -> Authority (domain) -> ...
  # This is the entity the multi-tenancy-template calls "Organization".
  #
  # `partner_id` NULL means client-owned: the customer signed up and manages
  # itself without an integrator. `payer` records who receives invoices for
  # this organization: the partner (integrator pays us and re-bills — the
  # default channel model) or the organization directly. An organization
  # without a partner can only pay for itself; `normalize_payer` keeps that
  # invariant ahead of the DB CHECK constraint.
  class Organization < ::PgORM::Base
    include PgORM::Timestamps

    table :organizations

    PAYER_PARTNER      = "partner"
    PAYER_ORGANIZATION = "organization"
    PAYERS             = [PAYER_PARTNER, PAYER_ORGANIZATION]

    default_primary_key id : UUID, autogenerated: true

    attribute name : String, sanitize: :text
    attribute description : String = "", sanitize: :common
    attribute payer : String = PAYER_PARTNER, mass_assignment: false
    attribute config : Hash(String, JSON::Any) = {} of String => JSON::Any

    attribute partner_id : UUID?
    belongs_to :partner, class_name: Partner, foreign_key: partner_id

    before_save :normalize_payer

    validates :name, presence: true

    validate ->(this : Organization) {
      unless PAYERS.includes?(this.payer)
        this.validation_error(:payer, "must be one of #{PAYERS.join(", ")}")
      end
    }

    validate ->(this : Organization) {
      # Friendlier error ahead of the DB's partial unique indexes: names are
      # unique within a partner's book, and unique among client-owned orgs.
      name = this.name
      return if name.nil? || name.empty?
      existing = Organization.where(partner_id: this.partner_id, name: name).first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id
      this.validation_error(:name, "an organization with this name already exists")
    }

    protected def normalize_payer
      self.payer = PAYER_ORGANIZATION if self.partner_id.nil?
    end

    # True when the customer manages itself without an integrator (no partner).
    def self_managed? : Bool
      self.partner_id.nil?
    end

    # Domains (authorities) owned by this organization.
    def authorities
      Authority.where(organization_id: self.id)
    end
  end
end
