require "uuid"
require "uuid/json"

require "./base/model"
require "./partner"

module PlaceOS::Model
  # A customer organisation (e.g. UCLA, Acadian) — the estate owner in the
  # PPT-526 hierarchy: Partner -> Organisation -> Authority (domain) -> ...
  # This is the entity the multi-tenancy-template calls "Organisation".
  #
  # `partner_id` NULL means client-owned: the customer signed up and manages
  # itself without an integrator. `payer` records who receives invoices for
  # this organisation: the partner (integrator pays us and re-bills — the
  # default channel model) or the organisation directly. An organisation
  # without a partner can only pay for itself; `normalize_payer` keeps that
  # invariant ahead of the DB CHECK constraint.
  class Organisation < ::PgORM::Base
    include PgORM::Timestamps

    table :organisations

    PAYER_PARTNER      = "partner"
    PAYER_ORGANISATION = "organisation"
    PAYERS             = [PAYER_PARTNER, PAYER_ORGANISATION]

    default_primary_key id : UUID, autogenerated: true

    attribute name : String, sanitize: :text
    attribute description : String = "", sanitize: :common
    attribute payer : String = PAYER_PARTNER, mass_assignment: false
    attribute config : Hash(String, JSON::Any) = {} of String => JSON::Any

    # The partner's own staff organisation: its admins and support users reach
    # every organisation under `partner_id`. Requires a partner.
    attribute partner_staff : Bool = false, mass_assignment: false

    attribute partner_id : UUID?
    belongs_to :partner, class_name: Partner, foreign_key: partner_id

    before_save :normalize_payer

    validates :name, presence: true

    validate ->(this : Organisation) {
      unless PAYERS.includes?(this.payer)
        this.validation_error(:payer, "must be one of #{PAYERS.join(", ")}")
      end
    }

    validate ->(this : Organisation) {
      if this.partner_staff && this.partner_id.nil?
        this.validation_error(:partner_staff, "requires a partner")
      end
    }

    validate ->(this : Organisation) {
      # Friendlier error ahead of the DB's partial unique indexes: names are
      # unique within a partner's book, and unique among client-owned orgs.
      name = this.name
      return if name.nil? || name.empty?
      existing = Organisation.where(partner_id: this.partner_id, name: name).first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id
      this.validation_error(:name, "an organisation with this name already exists")
    }

    protected def normalize_payer
      self.payer = PAYER_ORGANISATION if self.partner_id.nil?
    end

    # True when the customer manages itself without an integrator (no partner).
    def self_managed? : Bool
      self.partner_id.nil?
    end

    # Domains (authorities) owned by this organisation.
    def authorities
      Authority.where(organisation_id: self.id)
    end

    # Every organisation under the same partner, this one included.
    def partner_organisations
      Organisation.where(partner_id: self.partner_id)
    end

    # The staff organisations of a partner.
    def self.staff_of(partner_id : UUID)
      Organisation.where(partner_id: partner_id, partner_staff: true)
    end
  end
end
