require "uuid"
require "uuid/json"

require "./base/model"

module PlaceOS::Model
  # An integrator/reseller organisation (e.g. NTT) that brings clients onto
  # the platform and may manage them. The top of the PPT-526 hierarchy:
  # Partner -> Client -> Authority (domain) -> zones/systems/...
  #
  # `management = true` marks the platform operator's own organisation
  # (PlaceOS staff): members of a management partner may be granted
  # cluster-wide visibility. `parent_id` reserves a two-tier channel
  # (distributor -> reseller); it carries no behaviour yet.
  class Partner < ::PgORM::Base
    include PgORM::Timestamps

    table :partners

    default_primary_key id : UUID, autogenerated: true

    attribute name : String, sanitize: :text
    attribute description : String = "", sanitize: :common
    attribute management : Bool = false, mass_assignment: false
    attribute config : Hash(String, JSON::Any) = {} of String => JSON::Any

    attribute parent_id : UUID?
    belongs_to :parent, class_name: Partner, foreign_key: parent_id

    validates :name, presence: true

    validate ->(this : Partner) {
      # Friendlier error ahead of the DB's unique index.
      name = this.name
      return if name.nil? || name.empty?
      existing = Partner.where(name: name).first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id
      this.validation_error(:name, "a partner with this name already exists")
    }

    validate ->(this : Partner) {
      # The parent chain must not loop back to this partner.
      parent_id = this.parent_id
      return if parent_id.nil?
      if this.persisted? && parent_id == this.id
        this.validation_error(:parent_id, "a partner cannot be its own parent")
        return
      end
      seen = Set(UUID).new
      current = parent_id
      while current
        if this.persisted? && current == this.id
          this.validation_error(:parent_id, "parent chain forms a cycle")
          return
        end
        break unless seen.add?(current)
        current = Partner.find?(current).try(&.parent_id)
      end
    }

    # Immediate child partners (distributor -> reseller).
    def children
      Partner.where(parent_id: self.id)
    end

    # Organisations under this partner's book of business.
    def organisations
      Organisation.where(partner_id: self.id)
    end
  end
end
