require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
require "./user"
require "./email"

module PlaceOS::Model
  # An email queued for later processing/sending. Each row belongs to an
  # authority and to the user who triggered it. The actual content is
  # described by a `template` (a list of names resolving to a template) plus
  # `args` injected into it. `attachments`/`resource_attachments` reference
  # `Upload` ids; those ids are pruned automatically when an upload is
  # deleted (see `Upload#remove_from_pending_mail`). `zones` references zone
  # ids and is pruned when a zone is deleted (see `Zone#remove_array_references`).
  class PendingMail < ::PgORM::Base
    include PgORM::Timestamps
    # ElasticSearch indexing. Fields tagged `es_type: "keyword"` are indexed
    # for exact matching / filtering.
    include Neuroplastic

    table :pending_mail

    default_primary_key id : UUID, autogenerated: true

    # schedule a send for this time (or later); nil sends as soon as processed
    attribute send_at : Time? = nil

    # after which the email should not be sent
    attribute expiry : Time? = nil

    # recipients (exact match)
    attribute send_to : Array(String) = [] of String, es_type: "keyword"

    # names which resolve to the template to be sent
    attribute template : Array(String) = [] of String, es_type: "keyword"

    # values injected into the template. Restricted to JSON scalar values;
    # nested objects/arrays are rejected on deserialization.
    attribute args : Hash(String, String | Int64 | Float64 | Bool | Nil) = {} of String => (String | Int64 | Float64 | Bool | Nil)

    # upload id references. If an upload is deleted, its id is removed from
    # these arrays via `Upload`'s before_destroy callback.
    attribute resource_attachments : Array(String) = [] of String, es_type: "keyword"
    attribute attachments : Array(String) = [] of String, es_type: "keyword"

    attribute cc : Array(String) = [] of String, es_type: "keyword"
    attribute bcc : Array(String) = [] of String, es_type: "keyword"
    attribute send_from : String? = nil, es_type: "keyword"
    attribute reply_to : String? = nil, es_type: "keyword"

    # zone id references. If a zone is deleted, its id is removed from this
    # array via `Zone`'s before_destroy callback.
    attribute zones : Array(String) = [] of String, es_type: "keyword"

    # Monitoring: populated as the mail is processed. `sent_by` and
    # `rejected_reason` are free-form text (e.g. a worker/service name or a
    # human-readable reason).
    attribute sent_at : Time? = nil
    attribute sent_by : String? = nil, sanitize: :text, es_type: "keyword"
    attribute rejected_at : Time? = nil
    attribute rejected_reason : String? = nil, sanitize: :common

    # Free-form provenance, indexed for filtering (e.g. which service queued
    # the mail and an external reference/correlation id).
    attribute source_service : String? = nil, sanitize: :text, es_type: "keyword"
    attribute source_reference : String? = nil, sanitize: :text, es_type: "keyword"

    attribute authority_id : String, es_type: "keyword"
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    attribute user_id : String, es_type: "keyword"
    belongs_to :user, class_name: PlaceOS::Model::User

    # Validation
    ###############################################################################################

    validates :authority_id, presence: true
    validates :user_id, presence: true

    validate ->(this : PendingMail) {
      this.validation_error(:send_to, "requires at least one recipient") if this.send_to.empty?

      this.validate_emails(:send_to, this.send_to)
      this.validate_emails(:cc, this.cc)
      this.validate_emails(:bcc, this.bcc)

      if send_from = this.send_from.presence
        this.validation_error(:send_from, "'#{send_from}' is not a valid email") unless Email.new(send_from).valid?
      end

      if reply_to = this.reply_to.presence
        this.validation_error(:reply_to, "'#{reply_to}' is not a valid email") unless Email.new(reply_to).valid?
      end
    }

    protected def validate_emails(field : Symbol, addresses : Array(String))
      addresses.each do |address|
        validation_error(field, "'#{address}' is not a valid email") unless Email.new(address).valid?
      end
    end
  end
end
