require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
require "./email"
require "./history"
require "./signage_plugin"
require "./playlist"
require "./user"
require "./signage_template/layout"

module PlaceOS::Model
  # positions widget plugins over a signage display, changing its layout.
  # Attached to displays via `SignageTemplate::SystemTemplate`.
  class SignageTemplate < ::PgORM::Base
    include PgORM::Timestamps

    Log = ::Log.for(self)

    table :signage_template

    default_primary_key id : UUID, autogenerated: true

    attribute name : String, sanitize: :text
    attribute description : String? = nil, sanitize: :common
    attribute tags : Array(String) = [] of String, sanitize: :text

    attribute authority_id : String
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    # optional media item rendered behind the widgets
    # (cleared at the DB level if the item is deleted: ON DELETE SET NULL)
    attribute background_item_id : String? = nil
    belongs_to :background_item, class_name: PlaceOS::Model::Playlist::Item, foreign_key: background_item_id

    # widget placements, stored as a JSONB array
    attribute layouts : Array(Layout) = [] of Layout, converter: PlaceOS::Model::DBArrConverter(PlaceOS::Model::SignageTemplate::Layout)

    attribute full_screen_takeover : Bool = false

    # Approval
    ###############################################################################################

    attribute approval_requested : Bool = false, mass_assignment: false
    attribute requested_by_id : String?, mass_assignment: false

    attribute approved : Bool = false, mass_assignment: false
    attribute approved_by_id : String?, mass_assignment: false
    attribute approved_by_name : String?, sanitize: :text, mass_assignment: false
    attribute approved_by_email : PlaceOS::Model::Email?, format: "email", converter: PlaceOS::Model::EmailConverter, mass_assignment: false

    def approver=(user)
      self.approved_by_id = user.id.as(String)
      self.approved_by_name = user.name
      self.approved_by_email = user.email
      self.approved = true
    end

    # approved templates should not be edited in place, so drafts are
    # separate rows referencing the approved parent they were copied from.
    # Drafts are removed at the DB level when the parent is deleted
    # (ON DELETE CASCADE)
    attribute live_template_id : UUID? = nil
    belongs_to :live_template, class_name: PlaceOS::Model::SignageTemplate, foreign_key: live_template_id

    def draft? : Bool
      !live_template_id.nil?
    end

    # promotes this draft onto the approved template it references: copies
    # the display fields, records the approver on the live template and
    # removes the draft — all in a single transaction
    def approve_draft!(user_model_who_approved : User) : SignageTemplate
      raise ::PlaceOS::Model::Error.new("template #{id} is not a draft") unless draft?

      live = self.live_template
      ::PgORM::Database.transaction do
        live.background_item_id = self.background_item_id
        live.layouts = self.layouts
        live.full_screen_takeover = self.full_screen_takeover
        live.approver = user_model_who_approved
        live.save!
        self.destroy
      end
      live
    end

    # Helpers
    ###############################################################################################

    def system_templates
      SystemTemplate.where(template_id: self.id)
    end

    def systems
      sys_ids = system_templates.to_a.compact_map(&.control_system_id).uniq!
      ControlSystem.where(id: sys_ids)
    end

    def zones
      zone_ids = system_templates.to_a.compact_map(&.zone_id).uniq!
      Zone.where(id: zone_ids)
    end

    # Validation
    ###############################################################################################

    validates :name, presence: true
    validates :authority_id, presence: true

    # each layout must be structurally valid
    validate ->(this : SignageTemplate) {
      this.layouts.each_with_index do |layout, index|
        if message = layout.validation_message
          this.validation_error(:layouts, "layout #{index + 1}: #{message}")
        end
      end
    }

    # layout plugins must be widgets belonging to the same authority and the
    # provided params must satisfy the plugin's params schema
    validate ->(this : SignageTemplate) {
      plugin_ids = this.layouts.compact_map(&.plugin_id).uniq!
      return if plugin_ids.empty?

      plugins = SignagePlugin.where(id: plugin_ids).to_a.index_by(&.id.as(String))

      this.layouts.each_with_index do |layout, index|
        next unless plugin_id = layout.plugin_id

        unless plugin = plugins[plugin_id]?
          this.validation_error(:layouts, "layout #{index + 1}: plugin '#{plugin_id}' does not exist")
          next
        end

        unless plugin.plugin_type.widget?
          this.validation_error(:layouts, "layout #{index + 1}: plugin '#{plugin_id}' is not a widget")
        end

        unless plugin.authority_id == this.authority_id
          this.validation_error(:layouts, "layout #{index + 1}: plugin '#{plugin_id}' must belong to the same authority")
        end

        this.validate_layout_params(index, layout, plugin)
      end
    }

    protected def validate_layout_params(index : Int32, layout : Layout, plugin : SignagePlugin)
      properties = plugin.params["properties"]?.try(&.as_h?)

      layout.plugin_params.each_key do |key|
        unless properties.try(&.has_key?(key))
          validation_error(:layouts, "layout #{index + 1}: param '#{key}' does not exist in plugin params properties")
        end
      end

      if required = plugin.params["required"]?.try(&.as_a?)
        merged = plugin.defaults.merge(layout.plugin_params)
        required.each do |required_key|
          next unless key = required_key.as_s?
          unless merged.has_key?(key)
            validation_error(:layouts, "layout #{index + 1}: missing required param '#{key}'")
          end
        end
      end
    end

    # History
    ###############################################################################################

    before_save :record_template_history

    # tracks which fields changed on updates (creates and draft edits are
    # not recorded, history is captured when a draft is approved)
    protected def record_template_history
      return unless persisted?
      return if draft?

      changed_fields = [] of String
      changed_fields << "name" if name_changed?
      changed_fields << "description" if description_changed?
      changed_fields << "tags" if tags_changed?
      changed_fields << "background_item_id" if background_item_id_changed?
      changed_fields << "layouts" if layouts_changed?
      changed_fields << "full_screen_takeover" if full_screen_takeover_changed?
      changed_fields << "approval_requested" if approval_requested_changed?
      changed_fields << "approved" if approved_changed?
      changed_fields << "live_template_id" if live_template_id_changed?

      return if changed_fields.empty?

      History.create!(
        type: "template",
        resource_id: self.id.to_s,
        action: "updated",
        changed_fields: changed_fields,
      )
    rescue ex
      Log.error(exception: ex) { "failed to record signage template history for #{self.id}" }
    end
  end
end

require "./signage_template/*"
