require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
require "./history"
require "./signage_plugin"
require "./playlist"
require "./signage_template/layout"

module PlaceOS::Model
  # positions widget plugins over a signage display, changing its layout.
  # Attached to displays via `SignageTemplate::SystemTemplate`.
  class SignageTemplate < ::PgORM::Base
    include PgORM::Timestamps
    include Neuroplastic

    Log = ::Log.for(self)

    table :signage_template

    default_primary_key id : UUID, autogenerated: true

    attribute name : String, sanitize: :text, es_subfield: "keyword"
    attribute description : String? = nil, sanitize: :common
    attribute tags : Array(String) = [] of String, sanitize: :text, es_type: "keyword"

    attribute authority_id : String, es_type: "keyword"
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    # optional media item rendered behind the widgets
    # (cleared at the DB level if the item is deleted: ON DELETE SET NULL)
    attribute background_item_id : String? = nil, es_type: "keyword"
    belongs_to :background_item, class_name: PlaceOS::Model::Playlist::Item, foreign_key: background_item_id

    # widget placements, stored as a JSONB array. Not indexed in elastic.
    attribute layouts : Array(Layout) = [] of Layout, converter: PlaceOS::Model::DBArrConverter(PlaceOS::Model::SignageTemplate::Layout), es_ignore: true

    attribute full_screen_takeover : Bool = false

    # Helpers
    ###############################################################################################

    def system_templates
      SystemTemplate.where(template_id: self.id)
    end

    def systems
      sys_ids = system_templates.to_a.map(&.control_system_id).uniq!
      ControlSystem.where(id: sys_ids)
    end

    # Validation
    ###############################################################################################

    validates :name, presence: true
    validates :authority_id, presence: true

    # each layout must be structurally valid
    validate ->(this : SignageTemplate) {
      this.layouts.each_with_index do |layout, index|
        if message = layout.validation_message
          this.validation_error(:layouts, "layout #{index + 1}: #{message}")
        end
      end
    }

    # layout plugins must be widgets belonging to the same authority and the
    # provided params must satisfy the plugin's params schema
    validate ->(this : SignageTemplate) {
      plugin_ids = this.layouts.compact_map(&.plugin_id).uniq!
      return if plugin_ids.empty?

      plugins = SignagePlugin.where(id: plugin_ids).to_a.index_by(&.id.as(String))

      this.layouts.each_with_index do |layout, index|
        next unless plugin_id = layout.plugin_id

        unless plugin = plugins[plugin_id]?
          this.validation_error(:layouts, "layout #{index + 1}: plugin '#{plugin_id}' does not exist")
          next
        end

        unless plugin.plugin_type.widget?
          this.validation_error(:layouts, "layout #{index + 1}: plugin '#{plugin_id}' is not a widget")
        end

        unless plugin.authority_id == this.authority_id
          this.validation_error(:layouts, "layout #{index + 1}: plugin '#{plugin_id}' must belong to the same authority")
        end

        this.validate_layout_params(index, layout, plugin)
      end
    }

    protected def validate_layout_params(index : Int32, layout : Layout, plugin : SignagePlugin)
      properties = plugin.params["properties"]?.try(&.as_h?)

      layout.plugin_params.each_key do |key|
        unless properties.try(&.has_key?(key))
          validation_error(:layouts, "layout #{index + 1}: param '#{key}' does not exist in plugin params properties")
        end
      end

      if required = plugin.params["required"]?.try(&.as_a?)
        merged = plugin.defaults.merge(layout.plugin_params)
        required.each do |required_key|
          next unless key = required_key.as_s?
          unless merged.has_key?(key)
            validation_error(:layouts, "layout #{index + 1}: missing required param '#{key}'")
          end
        end
      end
    end

    # History
    ###############################################################################################

    before_save :record_template_history

    # tracks which fields changed on updates (creates are not recorded)
    protected def record_template_history
      return unless persisted?

      changed_fields = [] of String
      changed_fields << "name" if name_changed?
      changed_fields << "description" if description_changed?
      changed_fields << "tags" if tags_changed?
      changed_fields << "background_item_id" if background_item_id_changed?
      changed_fields << "layouts" if layouts_changed?
      changed_fields << "full_screen_takeover" if full_screen_takeover_changed?

      return if changed_fields.empty?

      History.create!(
        type: "template",
        resource_id: self.id.to_s,
        action: "updated",
        changed_fields: changed_fields,
      )
    rescue ex
      Log.error(exception: ex) { "failed to record signage template history for #{self.id}" }
    end
  end
end

require "./signage_template/*"
