require "json"
require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
require "./signage_ai_provider"
require "./user"

module PlaceOS::Model
  # One image generation or edit request.
  #
  # Candidates are written into `result["images"]` one at a time by the runner as
  # each vendor call finishes. Every write bumps `version`, which is what the long
  # polling endpoint compares against so a client can tell what it has already seen
  # (`updated_at` only has whole second resolution and cannot order two writes in
  # the same second).
  class SignageAIJob < ::PgORM::Base
    include PgORM::Timestamps
    include Neuroplastic

    Log = ::Log.for(self)

    table :signage_ai_jobs

    default_primary_key id : UUID, autogenerated: true

    enum Kind
      Generate
      Edit

      def to_s : String
        super.downcase
      end
    end

    enum State
      Queued
      Running
      Done
      Failed
      Cancelled

      def to_s : String
        super.downcase
      end

      def final?
        self == Done || self == Failed || self == Cancelled
      end
    end

    attribute authority_id : String, es_type: "keyword"
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    attribute provider_id : UUID? = nil, es_type: "keyword"
    belongs_to :provider, class_name: PlaceOS::Model::SignageAIProvider, foreign_key: provider_id

    # recorded as strings as well so a job survives its provider row being deleted
    # (named provider_type because `provider` is the belongs_to association above)
    attribute provider_type : String? = nil, es_type: "keyword"
    attribute model : String? = nil, es_type: "keyword"

    attribute user_id : String? = nil, es_type: "keyword"
    belongs_to :user, class_name: PlaceOS::Model::User, foreign_key: user_id
    attribute user_email : String? = nil, es_type: "keyword"
    attribute user_name : String? = nil, sanitize: :text

    # a refine points at the job it was refined from
    attribute parent_job_id : UUID? = nil, es_type: "keyword"

    attribute version : Int32 = 0
    attribute kind : Kind = Kind::Generate, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::SignageAIJob::Kind), es_type: "keyword"
    attribute state : State = State::Queued, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::SignageAIJob::State), es_type: "keyword"
    attribute cancel_requested : Bool = false
    attribute idempotency_key : String? = nil, es_type: "keyword"

    attribute candidates : Int32 = 1
    attribute images_produced : Int32 = 0

    attribute prompt : String? = nil, es_ignore: true
    attribute request : JSON::Any = JSON::Any.new({} of String => JSON::Any), es_ignore: true
    attribute result : JSON::Any = JSON::Any.new({} of String => JSON::Any), es_ignore: true

    attribute error_kind : String? = nil, es_type: "keyword"
    attribute error_message : String? = nil, sanitize: :text
    attribute upload_ids : Array(String) = [] of String, es_type: "keyword"

    attribute cost_units : Float64? = nil
    attribute latency_ms : Int64? = nil

    attribute started_at : Time? = nil
    attribute finished_at : Time? = nil

    validates :authority_id, presence: true

    def final? : Bool
      state.final?
    end

    # The candidate slots, in order. Entries are `null` until that candidate lands.
    def images : Array(JSON::Any)
      result["images"]?.try(&.as_a?) || [] of JSON::Any
    end

    # Walk back up a refine chain, oldest first. Bounded so a cycle cannot hang a request.
    def chain(limit : Int32 = 25) : Array(SignageAIJob)
      seen = [] of SignageAIJob
      current = self
      limit.times do
        parent_id = current.parent_job_id
        break unless parent_id
        parent = SignageAIJob.find?(parent_id)
        break unless parent
        seen.unshift(parent)
        current = parent
      end
      seen
    end

    # Write one candidate into result->'images'->index and bump the version, in a
    # single statement. Candidate fibers must never load, modify and save the row:
    # `save` writes the whole column and would drop entries written concurrently.
    def self.bump_image(id : UUID, index : Int32, image : JSON::Any | Hash(String, JSON::Any)) : Int32?
      payload = image.to_json
      ::PgORM::Database.connection do |db|
        db.query_one?(<<-SQL, id, index.to_s, payload, as: Int32)
          UPDATE signage_ai_jobs
          SET
            result = jsonb_set(
              CASE
                WHEN jsonb_typeof(result -> 'images') = 'array' THEN result
                ELSE jsonb_set(result, '{images}', '[]'::jsonb, true)
              END,
              ARRAY['images', $2],
              $3::jsonb,
              true
            ),
            images_produced = images_produced + 1,
            version = version + 1,
            updated_at = now()
          WHERE id = $1
          RETURNING version;
        SQL
      end
    end

    # Bump the version without touching the images, so a state change wakes a
    # long polling client too.
    def self.bump_version(id : UUID) : Int32?
      ::PgORM::Database.connection do |db|
        db.query_one?(<<-SQL, id, as: Int32)
          UPDATE signage_ai_jobs
          SET version = version + 1, updated_at = now()
          WHERE id = $1
          RETURNING version;
        SQL
      end
    end

    # Candidates requested by a user since a point in time, for the per user quota.
    def self.sum_candidates(user_id : String, since : Time) : Int32
      ::PgORM::Database.connection do |db|
        db.query_one(<<-SQL, user_id, since, as: Int64)
          SELECT COALESCE(SUM(candidates), 0)::bigint
          FROM signage_ai_jobs
          WHERE user_id = $1
            AND created_at >= $2
            AND state <> 'FAILED'
        SQL
      end.to_i32
    end

    # Candidates requested across a domain since a point in time, for the domain quota.
    def self.sum_candidates_for_authority(authority_id : String, since : Time) : Int32
      ::PgORM::Database.connection do |db|
        db.query_one(<<-SQL, authority_id, since, as: Int64)
          SELECT COALESCE(SUM(candidates), 0)::bigint
          FROM signage_ai_jobs
          WHERE authority_id = $1
            AND created_at >= $2
            AND state <> 'FAILED'
        SQL
      end.to_i32
    end

    # Jobs left running by a replica that went away.
    def self.stale(older_than : Time) : Array(SignageAIJob)
      where("state = 'RUNNING' AND started_at < ?", older_than).to_a
    end

    # Usage per provider and model, for the Backoffice usage tab.
    record UsageRow, provider : String, model : String, jobs : Int64, candidates : Int64,
      images_produced : Int64, cost_units : Float64 do
      include JSON::Serializable
    end

    def self.usage(authority_id : String, from : Time, to : Time) : Array(UsageRow)
      rows = [] of UsageRow
      ::PgORM::Database.connection do |db|
        db.query(<<-SQL, authority_id, from, to) do |rs|
          SELECT
            COALESCE(provider_type, 'unknown') AS provider,
            COALESCE(model, 'unknown') AS model,
            COUNT(*)::bigint AS jobs,
            COALESCE(SUM(candidates), 0)::bigint AS candidates,
            COALESCE(SUM(images_produced), 0)::bigint AS images_produced,
            COALESCE(SUM(cost_units), 0)::double precision AS cost_units
          FROM signage_ai_jobs
          WHERE authority_id = $1 AND created_at >= $2 AND created_at < $3
          GROUP BY 1, 2
          ORDER BY 1, 2
        SQL
          rs.each do
            rows << UsageRow.new(
              provider: rs.read(String),
              model: rs.read(String),
              jobs: rs.read(Int64),
              candidates: rs.read(Int64),
              images_produced: rs.read(Int64),
              cost_units: rs.read(Float64),
            )
          end
        end
      end
      rows
    end
  end
end
