require "json"
require "uuid"
require "uuid/json"

require "./base/model"
require "./authority"
require "./utilities/encryption"

module PlaceOS::Model
  # Vendor credentials used to generate or edit signage artwork.
  #
  # A row with a `nil` authority_id is the shared fallback, the same arrangement
  # `Storage` uses. Credentials are a JSON object whose shape depends on the
  # provider, encrypted at rest and never rendered by the API.
  class SignageAIProvider < ::PgORM::Base
    include PgORM::Timestamps
    include Neuroplastic

    Log = ::Log.for(self)

    table :signage_ai_providers

    default_primary_key id : UUID, autogenerated: true

    enum Provider
      OPENAI
      AZURE_OPENAI
      GOOGLE_VERTEX

      def google?
        self == GOOGLE_VERTEX
      end

      # OpenAI and Azure OpenAI speak the same request and response shape
      def openai_compatible?
        self == OPENAI || self == AZURE_OPENAI
      end
    end

    attribute name : String, sanitize: :text, es_subfield: "keyword"
    attribute provider : Provider = Provider::OPENAI, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::SignageAIProvider::Provider), es_type: "keyword"

    attribute authority_id : String? = nil, es_type: "keyword"
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    # encrypted JSON object, see `credentials_json`
    attribute credentials : String, mass_assignment: false, es_ignore: true

    # optional overrides. `endpoint` also lets a deployment point at a gateway or,
    # locally, at a stub vendor.
    attribute endpoint : String? = nil, sanitize: :text
    attribute location : String? = nil, sanitize: :text
    attribute default_model : String? = nil, sanitize: :text
    attribute allowed_models : Array(String) = [] of String, es_type: "keyword"

    attribute enabled : Bool = true
    attribute is_default : Bool = false

    # {"user_per_day": 60, "domain_per_month": 2000}
    attribute quotas : JSON::Any = JSON::Any.new({} of String => JSON::Any), es_ignore: true

    validates :name, presence: true
    validates :credentials, presence: true

    before_save do
      self.credentials = PlaceOS::Encryption.encrypt(credentials, level: level, id: encryption_id)
    end

    # The provider used for a domain: its own default, then its own first enabled
    # row, then the shared fallback.
    def self.default_for(authority_id : String?) : SignageAIProvider?
      if authority_id
        own = where(authority_id: authority_id, enabled: true).order(is_default: :desc, created_at: :asc).first?
        return own if own
      end
      where(authority_id: nil, enabled: true).order(is_default: :desc, created_at: :asc).first?
    end

    # Rows a domain may use: its own, plus the shared fallback.
    def self.available_for(authority_id : String?) : Array(SignageAIProvider)
      rows = where(authority_id: nil, enabled: true).to_a
      rows = where(authority_id: authority_id, enabled: true).to_a + rows if authority_id
      rows
    end

    def decrypt_credentials : String
      PlaceOS::Encryption.decrypt(credentials, level: level, id: encryption_id)
    end

    # Parsed credentials. Raises `Model::Error` when the stored value is not an object,
    # which is what a wrong `PLACE_SERVER_SECRET` looks like from here.
    def credentials_json : Hash(String, JSON::Any)
      parsed = JSON.parse(decrypt_credentials)
      parsed.as_h
    rescue JSON::ParseException | TypeCastError
      raise Model::Error.new("credentials for signage AI provider #{id} could not be read")
    end

    def credentials_json=(value : Hash(String, JSON::Any) | JSON::Any)
      self.credentials = value.to_json
    end

    def credentials_encrypted? : Bool
      PlaceOS::Encryption.is_encrypted?(credentials)
    end

    def quota(key : String) : Int32?
      quotas[key]?.try(&.as_i?)
    end

    # Rendered by the API in place of `to_json`: the same row without credentials.
    def as_json
      {
        id:             id.as(UUID).to_s,
        name:           name,
        provider:       provider.to_s,
        authority_id:   authority_id,
        endpoint:       endpoint,
        location:       location,
        default_model:  default_model,
        allowed_models: allowed_models,
        enabled:        enabled,
        is_default:     is_default,
        quotas:         quotas,
        created_at:     created_at.try(&.to_unix),
        updated_at:     updated_at.try(&.to_unix),
      }
    end

    private def level : PlaceOS::Encryption::Level
      PlaceOS::Encryption::Level::NeverDisplay
    end

    # Keyed on the domain rather than the row id: `id` is generated by the database
    # so it is not available while `before_save` runs on a new row.
    private def encryption_id : String
      authority_id || "shared"
    end
  end
end
