require "uuid"
require "uuid/json"

require "../base/model"
require "../authority"
require "../permissions"
require "./history"

module PlaceOS::Model
  # A named subsystem (signage, events, parking, workplace, ...) scoped to an
  # Authority. Holds the root of a Group tree and exposes the permission
  # query helpers used by the rest of the system.
  class GroupApplication < ::PgORM::Base
    include PgORM::Timestamps

    table :group_applications

    default_primary_key id : UUID, autogenerated: true

    attribute name : String
    attribute code : String
    attribute description : String = ""

    attribute authority_id : String
    belongs_to :authority, class_name: PlaceOS::Model::Authority

    validates :name, presence: true
    validates :code, presence: true
    validates :authority_id, presence: true

    include GroupHistory::Mixin

    # --------------------------------------------------------------------
    # Authority-scoped tree helpers
    #
    # Group trees are authority-wide; applications are overlays. The class
    # methods take an explicit `authority_id` so callers can use them
    # without a concrete `GroupApplication` instance. The instance methods
    # are thin conveniences that forward `self.authority_id`.
    # --------------------------------------------------------------------

    # The root Group for the given authority (at most one by schema).
    def self.root_group(authority_id : String) : Group?
      Group.where(authority_id: authority_id, parent_id: nil).first?
    end

    # All groups within the given authority.
    def self.groups(authority_id : String)
      Group.where(authority_id: authority_id)
    end

    def root_group : Group?
      self.class.root_group(self.authority_id)
    end

    def groups
      self.class.groups(self.authority_id)
    end

    # Groups participating in *this* application (via GroupApplicationMembership).
    def member_groups : Array(Group)
      ids = GroupApplicationMembership.where(application_id: self.id).to_a.map(&.group_id)
      return [] of Group if ids.empty?
      Group.where(id: ids).to_a
    end

    # --------------------------------------------------------------------
    # Permission query helpers
    # --------------------------------------------------------------------

    # Zone ids this user has any non-zero effective permission on, within
    # this application. Includes zones reached transitively (via ancestor
    # group membership and via ancestor zone GroupZone rows), minus
    # anything masked off by deny rows.
    def accessible_zone_ids(user_id : String) : Array(String)
      resolve_user_permissions(user_id).compact_map do |zone_id, perms|
        zone_id if perms != Permissions::None
      end
    end

    # Does this user have any non-zero effective permission on this zone
    # (directly or transitively)?
    def zone_accessible?(user_id : String, zone_id : String) : Bool
      effective_permissions(user_id, zone_id) != Permissions::None
    end

    # Effective permission bitmask for (user, zone) in this application.
    def effective_permissions(user_id : String, zone_id : String) : Permissions
      resolve_user_permissions(user_id)[zone_id]? || Permissions::None
    end

    # Effective permissions across a batch of zones. For every zone, the
    # closest applicable grant in that zone's own ancestry wins (replace
    # semantics — same rule as the single-zone form). Results are OR'd
    # across the list: this answers "what can the user do if *any* of
    # these zones is in play?". Zones with no applicable grant contribute
    # nothing. Returns `Permissions::None` for an empty list or for a
    # user who can't reach any of the supplied zones.
    #
    # Batched version of `effective_permissions(user_id, zone_id)`.
    # Cheaper than N individual calls: the underlying resolve happens
    # once and each zone is then a hash lookup.
    def effective_permissions(user_id : String, zone_ids : Array(String)) : Permissions
      return Permissions::None if zone_ids.empty?
      resolved = resolve_user_permissions(user_id)
      zone_ids.reduce(Permissions::None) do |acc, zid|
        acc | (resolved[zid]? || Permissions::None)
      end
    end

    # Resolve the full `{zone_id => Permissions}` map for the user in this
    # application.
    #
    # Rules, in English:
    # - User's effective perms on a group G = closest ancestor (up the group
    #   tree, inclusive) that the user has an explicit GroupUser entry on
    #   (replace semantics).
    # - A GroupZone(owner, anchor) grants access starting at `anchor` and
    #   propagating down the zone tree, unless a more-specific GroupZone
    #   on the same owner exists at a descendant zone (replace on zone tree),
    #   or a `deny` row for the same owner sits on the path (masks off).
    # - For each grant reaching a zone Z:
    #     - If Z == anchor: the user's perms come from `owner` itself.
    #     - If Z is a strict descendant of anchor: the user's perms come
    #       from the *deepest group in `owner`'s subtree where the user has
    #       an explicit GroupUser entry*. This is what makes an explicit
    #       descendant membership override an ancestor group's inherited
    #       grant. If no such explicit descendant exists, we fall back to
    #       `owner` (transitive membership still counts).
    # - Final perms at Z = OR across every contributing grant.
    private def resolve_user_permissions(user_id : String) : Hash(String, Permissions)
      result = {} of String => Permissions
      direct_memberships = user_direct_memberships(user_id)
      return result if direct_memberships.empty?
      # Walk the full authority-wide group tree — the user's explicit
      # membership on any group transitively propagates along the tree
      # regardless of which application we're resolving for.
      authority_groups = Group.where(authority_id: self.authority_id).to_a
      return result if authority_groups.empty?

      parent_of = {} of UUID => UUID
      all_group_ids = [] of UUID
      authority_groups.each do |g|
        gid = g.id.not_nil!
        all_group_ids << gid
        if (parent = g.parent_id)
          parent_of[gid] = parent
        end
      end

      effective_memberships = walk_up_memberships(direct_memberships, all_group_ids, parent_of)
      group_depths = compute_group_depths(all_group_ids, parent_of)
      group_descendants = compute_group_descendants(all_group_ids, parent_of)

      # Only groups that are members of *this* application contribute grants.
      member_group_ids = [] of UUID
      GroupApplicationMembership.where(application_id: self.id).each do |m|
        member_group_ids << m.group_id
      end
      return result if member_group_ids.empty?

      zone_children = zone_children_map
      rows_by_group = Hash(UUID, Array(GroupZone)).new
      GroupZone.where(group_id: member_group_ids).each do |gz|
        (rows_by_group[gz.group_id] ||= [] of GroupZone) << gz
      end

      rows_by_group.each do |owner_id, rows|
        # Which zones does *this* owner have direct rows on? Used to apply
        # replace-on-zone-tree semantics during the walk.
        by_zone = {} of String => GroupZone
        rows.each { |r| by_zone[r.zone_id] = r }

        rows.each do |row|
          grant_perms = row.deny ? Permissions::None : Permissions.new(row.permissions)
          next if grant_perms == Permissions::None

          reaching_descendant = deepest_explicit_in_subtree(
            owner_id, direct_memberships, group_descendants, group_depths,
          )
          descendant_perms = effective_memberships[reaching_descendant]?

          anchor_perms = effective_memberships[owner_id]?

          stack = [row.zone_id]
          until stack.empty?
            zone_id = stack.pop
            # Stop at any more-specific row for this owner — that row drives
            # its own subtree walk.
            next if zone_id != row.zone_id && by_zone.has_key?(zone_id)

            user_perms = zone_id == row.zone_id ? anchor_perms : descendant_perms
            if user_perms
              contribution = user_perms & grant_perms
              if contribution != Permissions::None
                result[zone_id] = (result[zone_id]? || Permissions::None) | contribution
              end
            end

            if (children = zone_children[zone_id]?)
              children.each { |c| stack << c }
            end
          end
        end
      end

      result
    end

    # User's *explicit* GroupUser rows, joined through Group to scope to
    # this authority.
    private def user_direct_memberships(user_id : String) : Hash(UUID, Permissions)
      direct = {} of UUID => Permissions
      sql = <<-SQL
        SELECT gu.group_id, gu.permissions
        FROM group_users gu
        INNER JOIN groups g ON g.id = gu.group_id
        WHERE gu.user_id = $1 AND g.authority_id = $2
      SQL
      args = [user_id.as(::PgORM::Value), self.authority_id.as(::PgORM::Value)]
      ::PgORM::Database.connection do |conn|
        conn.query_all(sql, args: args) do |rs|
          gid = rs.read(UUID)
          perms = rs.read(Int32)
          direct[gid] = Permissions.new(perms)
        end
      end
      direct
    end

    # Walk up the group tree from every group; each group's effective perms
    # = closest ancestor (inclusive) with an explicit entry. Groups without
    # any explicit ancestor entry are omitted.
    private def walk_up_memberships(
      direct : Hash(UUID, Permissions),
      all_group_ids : Array(UUID),
      parent_of : Hash(UUID, UUID),
    ) : Hash(UUID, Permissions)
      effective = {} of UUID => Permissions
      all_group_ids.each do |gid|
        current = gid
        loop do
          if (p = direct[current]?)
            effective[gid] = p
            break
          end
          next_parent = parent_of[current]?
          break if next_parent.nil?
          current = next_parent
        end
      end
      effective
    end

    private def compute_group_depths(
      all_group_ids : Array(UUID),
      parent_of : Hash(UUID, UUID),
    ) : Hash(UUID, Int32)
      depths = {} of UUID => Int32
      all_group_ids.each do |gid|
        depth = 0
        current = gid
        loop do
          parent = parent_of[current]?
          break if parent.nil?
          depth += 1
          current = parent
        end
        depths[gid] = depth
      end
      depths
    end

    private def compute_group_descendants(
      all_group_ids : Array(UUID),
      parent_of : Hash(UUID, UUID),
    ) : Hash(UUID, Array(UUID))
      children = {} of UUID => Array(UUID)
      parent_of.each do |child, parent|
        (children[parent] ||= [] of UUID) << child
      end

      descendants = {} of UUID => Array(UUID)
      all_group_ids.each do |root|
        collected = [] of UUID
        stack = [root]
        until stack.empty?
          node = stack.pop
          collected << node
          children[node]?.try &.each { |c| stack << c }
        end
        descendants[root] = collected
      end
      descendants
    end

    # Deepest group in `owner`'s subtree (inclusive) that has a direct
    # GroupUser entry for this user. Falls back to `owner` if none.
    private def deepest_explicit_in_subtree(
      owner : UUID,
      direct : Hash(UUID, Permissions),
      group_descendants : Hash(UUID, Array(UUID)),
      group_depths : Hash(UUID, Int32),
    ) : UUID
      candidates = group_descendants[owner]? || [owner]
      best = owner
      best_depth = group_depths[owner]? || 0
      found_explicit = direct.has_key?(owner)
      candidates.each do |gid|
        next unless direct.has_key?(gid)
        depth = group_depths[gid]? || 0
        if !found_explicit || depth > best_depth
          best = gid
          best_depth = depth
          found_explicit = true
        end
      end
      best
    end

    # Build a zone → children lookup for the full zone table. Zones are
    # typically a modest number and we need arbitrary subtree walks, so a
    # single pass here is cheaper than per-group recursive CTEs.
    private def zone_children_map : Hash(String, Array(String))
      children = {} of String => Array(String)
      sql = %(SELECT id, parent_id FROM "zone" WHERE parent_id IS NOT NULL)
      ::PgORM::Database.connection do |conn|
        conn.query(sql) do |rs|
          rs.each do
            id = rs.read(String)
            parent_id = rs.read(String)
            (children[parent_id] ||= [] of String) << id
          end
        end
      end
      children
    end

    # For a single group, walk down from each explicit GroupZone row.
    # A more-specific GroupZone row overrides its ancestor's grant
    # (replace). A deny row zeroes out its subtree (so `result` gets no
    # entry for zones in a denied subtree from this group's perspective).
    private def zone_grants_for_group(
      rows : Array(GroupZone),
      zone_children : Hash(String, Array(String)),
    ) : Hash(String, Permissions)
      grants = {} of String => Permissions
      by_zone = rows.to_h { |r| {r.zone_id, r} }

      rows.each do |row|
        effective = row.deny ? Permissions::None : Permissions.new(row.permissions)
        stack = [row.zone_id]
        until stack.empty?
          zone_id = stack.pop
          # Stop at any more-specific GroupZone row; that row drives its
          # own subtree walk.
          next if zone_id != row.zone_id && by_zone.has_key?(zone_id)
          grants[zone_id] = effective unless effective == Permissions::None
          zone_children[zone_id].each { |cid| stack << cid } if zone_children.has_key?(zone_id)
        end
      end
      grants
    end

    # --------------------------------------------------------------------
    # GroupHistory hooks
    # --------------------------------------------------------------------

    protected def group_history_resource_id : String
      self.id.to_s
    end

    protected def group_history_application_id : UUID?
      self.id
    end

    protected def group_history_group_id : UUID?
      nil
    end
  end
end
