require "uuid"
require "uuid/json"

require "../base/model"
require "../user"

module PlaceOS::Model
  # Audit trail for changes to Group-system models. Written inside the
  # same transaction as the triggering save/destroy via each model's
  # after-callbacks.
  #
  # `user_id` is nullable: it's SET NULL (via the FK) when the acting
  # user is later deleted. `email` is preserved so the audit trail stays
  # readable even after user deletion.
  class GroupHistory < ::PgORM::Base
    table :group_history

    default_primary_key id : UUID, autogenerated: true

    attribute application_id : UUID?
    attribute group_id : UUID?
    attribute user_id : String?
    attribute email : String
    attribute action : String
    attribute resource_type : String
    attribute resource_id : String
    attribute changed_fields : Array(String) = [] of String
    attribute created_at : Time = -> { Time.utc }

    validates :email, presence: true
    validates :action, presence: true
    validates :resource_type, presence: true
    validates :resource_id, presence: true

    before_create do
      self.created_at = Time.utc
    end

    # True once the acting user has been deleted and their reference
    # nulled out. `email` remains set so the audit trail is still useful.
    def user_deleted? : Bool
      user_id.nil?
    end
  end

  # Mixin that injects the GroupHistory recording machinery into a model.
  #
  # Including class must provide four small hook methods that tell the
  # mixin *what* to write:
  #
  #   protected def group_history_resource_type : String    # e.g. "group"
  #   protected def group_history_resource_id : String      # e.g. self.id.to_s
  #   protected def group_history_application_id : UUID?    # or nil
  #   protected def group_history_group_id : UUID?          # or nil
  #
  # Optionally override `group_history_changed_fields` to strip sensitive
  # attributes (see `GroupInvitation`).
  #
  # The mixin installs:
  # - three virtual (non-persisted, non-serialised) properties:
  #   `acting_user`, `was_new_record?`, `captured_changed_fields`.
  # - `before_save :capture_history_state` — snapshots `new_record?` and
  #   the changed attribute list before they're cleared by the save.
  # - `after_save :record_history_save` — writes a `"create"` or
  #   `"update"` row iff `acting_user` is set and (for updates) at least
  #   one attribute changed.
  # - `after_destroy :record_history_destroy` — writes a `"delete"` row
  #   iff `acting_user` is set.
  module GroupHistory::Mixin
    macro included
      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property acting_user : ::PlaceOS::Model::User?

      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property? was_new_record : Bool = false

      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property captured_changed_fields : Array(String) = [] of String

      before_save :capture_history_state
      after_save :record_history_save
      after_destroy :record_history_destroy

      protected def capture_history_state
        self.was_new_record = new_record?
        self.captured_changed_fields = was_new_record? ? attributes.keys.map(&.to_s) : changed_attributes.keys.map(&.to_s)
      end

      protected def record_history_save
        user = acting_user
        return unless user
        action = was_new_record? ? "create" : "update"
        fields = group_history_changed_fields
        return if action == "update" && fields.empty?
        ::PlaceOS::Model::GroupHistory.create!(
          application_id: group_history_application_id,
          group_id: group_history_group_id,
          user_id: user.id,
          email: user.email.to_s,
          action: action,
          resource_type: group_history_resource_type,
          resource_id: group_history_resource_id,
          changed_fields: fields,
        )
      end

      protected def record_history_destroy
        user = acting_user
        return unless user
        ::PlaceOS::Model::GroupHistory.create!(
          application_id: group_history_application_id,
          group_id: group_history_group_id,
          user_id: user.id,
          email: user.email.to_s,
          action: "delete",
          resource_type: group_history_resource_type,
          resource_id: group_history_resource_id,
          changed_fields: [] of String,
        )
      end

      # Default: everything captured in `before_save`. Override to strip
      # sensitive attributes out of the audit trail.
      protected def group_history_changed_fields : Array(String)
        captured_changed_fields
      end

      def group_history_resource_type : String
        self.class.to_s.split("::").last.underscore
      end
    end

    abstract def group_history_resource_id : String
    abstract def group_history_application_id : UUID?
    abstract def group_history_group_id : UUID?
  end
end
