require "digest/sha256"
require "random/secure"
require "uuid"
require "uuid/json"

require "../base/model"
require "../group"
require "../permissions"
require "./history"

module PlaceOS::Model
  # Grants a user who is not yet in the system (or external) access to a
  # group via a shared secret. The plaintext secret is generated at
  # creation time and returned to the caller *once*; only its SHA256
  # digest is persisted. Accepting an invitation materialises it into a
  # GroupUser and then destroys the invitation.
  class GroupInvitation < ::PgORM::Base
    include PgORM::Timestamps

    table :group_invitations

    default_primary_key id : UUID, autogenerated: true

    attribute email : String
    attribute secret_digest : String
    attribute permissions : Int32 = 0
    attribute expires_at : Time?

    attribute group_id : UUID
    belongs_to :group, class_name: Group, foreign_key: group_id

    # Plaintext secret — only set transiently on newly-created invitations
    # (by the `.build_with_secret` factory). Never persisted, never
    # serialised. Callers must capture this before the invitation is
    # handed off to any other consumer.
    @[JSON::Field(ignore: true)]
    @[YAML::Field(ignore: true)]
    property plaintext_secret : String?

    validates :email, presence: true
    validates :secret_digest, presence: true
    validates :group_id, presence: true

    before_save :normalise_email

    include GroupHistory::Mixin

    # Build a fresh invitation, generating a cryptographically strong
    # secret. The returned instance exposes `.plaintext_secret` *only until
    # the current process ends*; it is not reloadable from the database.
    def self.build_with_secret(
      group : Group,
      email : String,
      permissions : Permissions = Permissions::None,
      expires_at : Time? = nil,
    ) : self
      plaintext = Random::Secure.urlsafe_base64(32)
      invitation = new(
        group_id: group.id.not_nil!,
        email: email,
        secret_digest: digest_secret(plaintext),
        permissions: permissions.to_i,
        expires_at: expires_at,
      )
      invitation.plaintext_secret = plaintext
      invitation
    end

    # SHA256 hex digest of a plaintext secret.
    def self.digest_secret(plaintext : String) : String
      Digest::SHA256.hexdigest(plaintext)
    end

    # Find an invitation by its plaintext secret (constant cost; the
    # unique index is on `secret_digest`). Returns nil if no match or the
    # invitation has expired.
    def self.find_by_secret?(plaintext : String) : self?
      invitation = where(secret_digest: digest_secret(plaintext)).first?
      return nil if invitation.nil?
      return nil if invitation.expired?
      invitation
    end

    def permission_flags : Permissions
      Permissions.new(self.permissions)
    end

    def permission_flags=(flags : Permissions)
      self.permissions = flags.to_i
    end

    def expired? : Bool
      expiry = expires_at
      return false if expiry.nil?
      Time.utc > expiry
    end

    # Accept the invitation for the given user. Creates (or updates) a
    # GroupUser row with the invitation's permissions, then destroys the
    # invitation. Raises if the invitation has expired.
    def accept!(user : User) : GroupUser
      raise ::PgORM::Error.new("invitation expired") if expired?
      existing = GroupUser.where(user_id: user.id, group_id: self.group_id).first?
      gu = existing || GroupUser.new(user_id: user.id.not_nil!, group_id: self.group_id)
      gu.permissions = self.permissions
      gu.acting_user = user
      gu.save!
      self.acting_user = user
      destroy
      gu
    end

    protected def normalise_email
      self.email = self.email.strip.downcase
    end

    protected def group_history_resource_id : String
      self.id.to_s
    end

    protected def group_history_group_id : UUID?
      self.group_id
    end

    # Treat the SHA256 digest as sensitive even post-hashing — keep it
    # out of the audit trail's changed_fields list.
    protected def group_history_changed_fields : Array(String)
      captured_changed_fields.reject("secret_digest")
    end
  end
end
