-- +micrate Up
-- SQL in section 'Up' is executed when this migration is applied

-- Table created by rails migration:
-- class CreateDoorkeeperOpenidConnectTables < ActiveRecord::Migration[8.1]
--   create_table :oauth_openid_requests do |t|
--     t.references :access_grant, null: false, index: true
--     t.string :nonce, null: false
--   end
--   add_foreign_key :oauth_openid_requests, :oauth_access_grants,
--                   column: :access_grant_id, on_delete: :cascade
-- end

CREATE TABLE IF NOT EXISTS oauth_openid_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_grant_id BIGINT NOT NULL,
  nonce TEXT NOT NULL
);

-- index that Rails would add for t.references ... index: true
CREATE INDEX IF NOT EXISTS idx_oauth_openid_requests_on_access_grant_id
  ON oauth_openid_requests (access_grant_id);

-- foreign key with ON DELETE CASCADE
ALTER TABLE oauth_openid_requests
  ADD CONSTRAINT fk_oauth_openid_requests_access_grant
  FOREIGN KEY (access_grant_id)
  REFERENCES oauth_access_grants (id)
  ON DELETE CASCADE;

-- +micrate Down
-- SQL section 'Down' is executed when this migration is rolled back

DROP TABLE IF EXISTS oauth_openid_requests;
