require "uuid"
require "uuid/json"

require "../base/model"
require "../control_system"
require "../converter/json_string"
require "../playlist/schedule"
require "../signage_template"

module PlaceOS::Model
  # junction attaching a SignageTemplate to a ControlSystem. A row with a
  # `schedule` shows the template during that schedule; a row without one is
  # the default template for the pairing (at most one, enforced by a partial
  # unique index). Surrogate UUID pk as the same template may be attached to
  # the same system multiple times with different schedules.
  class SignageTemplate::SystemTemplate < ::PgORM::Base
    include PgORM::Timestamps

    table :system_templates

    default_primary_key id : UUID, autogenerated: true

    attribute control_system_id : String
    belongs_to :control_system, class_name: PlaceOS::Model::ControlSystem, foreign_key: control_system_id

    attribute template_id : UUID
    belongs_to :template, class_name: PlaceOS::Model::SignageTemplate, foreign_key: template_id

    # when the template applies; nil means this is the default template
    attribute schedule : Playlist::Schedule? = nil, converter: OptionalRecordConverter(PlaceOS::Model::Playlist::Schedule)

    def default? : Bool
      schedule.nil?
    end

    # Validation
    ###############################################################################################

    validates :control_system_id, presence: true
    validates :template_id, presence: true

    # a schedule, when present, must be valid
    validate ->(this : SystemTemplate) {
      if schedule = this.schedule
        if message = schedule.validation_message
          this.validation_error(:schedule, message)
        end
      end
    }

    # friendly pre-check for the partial unique index (the DB constraint
    # remains the source of truth)
    validate ->(this : SystemTemplate) {
      return unless this.schedule.nil?

      existing = SystemTemplate
        .where("control_system_id = ? AND template_id = ? AND schedule IS NULL", this.control_system_id, this.template_id)
        .first?
      return if existing.nil?
      return if this.persisted? && existing.id == this.id

      this.validation_error(:schedule, "system already has a default entry for this template")
    }
  end
end
