require "uuid"
require "uuid/json"

require "../base/model"
require "../control_system"
require "../converter/json_string"
require "../playlist/schedule"
require "../signage_template"
require "../zone"

module PlaceOS::Model
  # junction attaching a SignageTemplate to a ControlSystem or a Zone
  # (exactly one of the two). A row with a `schedule` shows the template
  # during that schedule; a row without one is the default template for the
  # pairing (at most one, enforced by a partial unique index). Surrogate
  # UUID pk as the same template may be attached to the same system or zone
  # multiple times with different schedules.
  class SignageTemplate::SystemTemplate < ::PgORM::Base
    include PgORM::Timestamps

    table :system_templates

    default_primary_key id : UUID, autogenerated: true

    attribute control_system_id : String? = nil
    belongs_to :control_system, class_name: PlaceOS::Model::ControlSystem, foreign_key: control_system_id

    attribute zone_id : String? = nil
    belongs_to :zone, class_name: PlaceOS::Model::Zone, foreign_key: zone_id

    attribute template_id : UUID
    belongs_to :template, class_name: PlaceOS::Model::SignageTemplate, foreign_key: template_id

    # when the template applies; nil means this is the default template
    attribute schedule : Playlist::Schedule? = nil, converter: OptionalRecordConverter(PlaceOS::Model::Playlist::Schedule)

    def default? : Bool
      schedule.nil?
    end

    # Validation
    ###############################################################################################

    validates :template_id, presence: true

    # templates attach to exactly one of a control system or a zone
    validate ->(this : SystemTemplate) {
      if this.control_system_id.presence && this.zone_id.presence
        this.validation_error(:zone_id, "cannot be set at the same time as control_system_id")
      elsif this.control_system_id.presence.nil? && this.zone_id.presence.nil?
        this.validation_error(:control_system_id, "either control_system_id or zone_id must be set")
      end
    }

    # a schedule, when present, must be valid
    validate ->(this : SystemTemplate) {
      if schedule = this.schedule
        if message = schedule.validation_message
          this.validation_error(:schedule, message)
        end
      end
    }

    # friendly pre-check for the partial unique index (the DB constraint
    # remains the source of truth)
    validate ->(this : SystemTemplate) {
      return unless this.schedule.nil?

      existing = if sys_id = this.control_system_id.presence
                   SystemTemplate
                     .where("control_system_id = ? AND template_id = ? AND schedule IS NULL", sys_id, this.template_id)
                     .first?
                 elsif zone_id = this.zone_id.presence
                   SystemTemplate
                     .where("zone_id = ? AND template_id = ? AND schedule IS NULL", zone_id, this.template_id)
                     .first?
                 end
      return if existing.nil?
      return if this.persisted? && existing.id == this.id

      this.validation_error(:schedule, "a default entry already exists for this template")
    }
  end
end
