name: CI
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  style:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        crystal:
          - latest
          - nightly
          - 1.0.0
    container:
      image: crystallang/crystal:${{ matrix.crystal }}
    services:
      rethink:
        image: rethinkdb:2.4
        ports:
        - 29015:29015
        - 28015:28015
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/lib
          key: ${{ hashFiles('shard.*') }}
      - run: shards install --ignore-crystal-version
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Tests
        run: crystal spec --error-trace -v --order=random --no-color
      - name: Tests Multithreaded
        run: crystal spec --error-trace -v --order=random --no-color -Dpreview_mt

  publish:
    if: github.ref == 'refs/head/master'
    needs: test
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Run `crystal tool docs`
        run: crystal tool docs
      - name: Publish to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: ./docs
          target-branch: docs
