name: CI
on:
  push:
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
    with:
      cache_shards: false

  publish:
    needs: test
    uses: PlaceOS/.github/.github/workflows/publish-crystal-docs.yml@feat/crystal-docs
