name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight 

jobs:
  style:
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest
    steps:
      - uses: actions/checkout@v7.0.1
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v1.0.0

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
