require "uuid"
require "uuid/json"

require "../base/model"
require "../booking"
require "./rate_card"
require "./booking_quote_history"

module PlaceOS::Model
  class BookingQuote < ::PgORM::Base
    include PgORM::Timestamps
    include BookingQuoteHistory::Mixin

    table :booking_quotes

    default_primary_key id : UUID, autogenerated: true

    enum QuoteStatus
      DRAFT
      ACCEPTED
      SUPERSEDED
      CANCELLED
    end

    attribute booking_id : Int64
    belongs_to :booking, class_name: Booking, foreign_key: booking_id

    attribute rate_card_id : UUID?
    belongs_to :rate_card, class_name: RateCard, foreign_key: rate_card_id

    attribute status : QuoteStatus = QuoteStatus::DRAFT, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::BookingQuote::QuoteStatus)

    attribute subtotal_cents : Int32 = 0
    attribute tax_cents : Int32 = 0
    attribute total_cents : Int32 = 0

    attribute currency : String = "AUD"
    attribute metadata : JSON::Any = JSON::Any.new({} of String => JSON::Any)

    attribute accepted_at : Time?, converter: Time::EpochConverterOptional

    validates :booking_id, presence: true

    validate ->(this : BookingQuote) do
      if this.subtotal_cents < 0
        this.validation_error(:subtotal_cents, "must be greater than or equal to 0")
      end

      if this.tax_cents < 0
        this.validation_error(:tax_cents, "must be greater than or equal to 0")
      end

      if this.total_cents < 0
        this.validation_error(:total_cents, "must be greater than or equal to 0")
      end
    end

    protected def booking_quote_history_quote_id : UUID
      id.not_nil!
    end
  end
end
