require "uuid"
require "uuid/json"

require "../base/model"
require "./booking_quote"
require "./booking_quote_history"
require "./pricing_rule"

module PlaceOS::Model
  module NumericToFloat64Converter
    def self.from_rs(rs : ::DB::ResultSet) : Float64
      rs.read(::PG::Numeric).to_f64
    end

    def self.from_json(pull : JSON::PullParser) : Float64
      raw = pull.read_raw
      raw.to_f64
    end

    def self.to_json(value : Float64 | Nil)
      value
    end

    def self.to_json(value : Float64 | Nil, builder)
      value.try &.to_json(builder)
    end
  end

  class BookingQuoteLineItem < ::PgORM::Base
    include PgORM::Timestamps
    include BookingQuoteHistory::Mixin

    table :booking_quote_line_items

    default_primary_key id : UUID, autogenerated: true

    attribute quote_id : UUID
    belongs_to :quote, class_name: BookingQuote, foreign_key: quote_id

    attribute pricing_rule_id : UUID?
    belongs_to :pricing_rule, class_name: PricingRule, foreign_key: pricing_rule_id

    attribute description : String

    attribute charge_category : PricingRule::ChargeCategory, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::PricingRule::ChargeCategory)
    attribute charge_basis : PricingRule::ChargeBasis, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::PricingRule::ChargeBasis)

    attribute quantity : Float64 = 1.0, converter: PlaceOS::Model::NumericToFloat64Converter

    attribute unit_amount_cents : Int32
    attribute total_amount_cents : Int32

    attribute approved : Bool = false
    attribute metadata : JSON::Any = JSON::Any.new({} of String => JSON::Any)

    validates :quote_id, presence: true
    validates :description, presence: true

    validate ->(this : BookingQuoteLineItem) do
      if this.quantity < 0.0
        this.validation_error(:quantity, "must be greater than or equal to 0")
      end
    end

    protected def booking_quote_history_quote_id : UUID
      quote_id
    end

    protected def booking_quote_history_changed_fields : Array(String)
      captured_changed_fields.map { |field| "line_item.#{field}" }
    end
  end
end
