require "uuid"
require "uuid/json"

require "../base/model"
require "../user"

module PlaceOS::Model
  class BookingQuoteHistory < ::PgORM::Base
    table :booking_quote_history

    default_primary_key id : UUID, autogenerated: true

    attribute quote_id : UUID
    attribute user_id : String?
    attribute email : String
    attribute action : String
    attribute changed_fields : Array(String) = [] of String
    attribute created_at : Time = -> { Time.utc }

    validates :quote_id, presence: true
    validates :email, presence: true
    validates :action, presence: true

    before_create do
      self.created_at = Time.utc
    end

    def user_deleted? : Bool
      user_id.nil?
    end

    def self.for_quote(quote_id : UUID) : Array(self)
      find_all_by_sql(
        "SELECT * FROM booking_quote_history WHERE quote_id = $1 ORDER BY created_at ASC",
        quote_id
      )
    end
  end

  module BookingQuoteHistory::Mixin
    macro included
      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property acting_user : ::PlaceOS::Model::User?

      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property? was_new_record : Bool = false

      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property captured_changed_fields : Array(String) = [] of String

      before_save :capture_booking_quote_history_state
      after_save :record_booking_quote_history_save
      after_destroy :record_booking_quote_history_destroy

      protected def capture_booking_quote_history_state
        self.was_new_record = new_record?
        self.captured_changed_fields = was_new_record? ? attributes.keys.map(&.to_s) : changed_attributes.keys.map(&.to_s)
      end

      protected def record_booking_quote_history_save
        user = acting_user
        return unless user
        action = was_new_record? ? "create" : "update"
        fields = booking_quote_history_changed_fields
        return if action == "update" && fields.empty?

        ::PlaceOS::Model::BookingQuoteHistory.create!(
          quote_id: booking_quote_history_quote_id,
          user_id: user.id,
          email: user.email.to_s,
          action: action,
          changed_fields: fields,
        )
      end

      protected def record_booking_quote_history_destroy
        user = acting_user
        return unless user

        ::PlaceOS::Model::BookingQuoteHistory.create!(
          quote_id: booking_quote_history_quote_id,
          user_id: user.id,
          email: user.email.to_s,
          action: "delete",
          changed_fields: [] of String,
        )
      end

      protected def booking_quote_history_changed_fields : Array(String)
        captured_changed_fields
      end
    end

    abstract def booking_quote_history_quote_id : UUID
  end
end
