require "uuid"
require "uuid/json"

require "../base/model"
require "../booking"
require "./booking_quote"
require "./booking_quote_history"

module PlaceOS::Model
  class BookingPayment < ::PgORM::Base
    include PgORM::Timestamps
    include BookingQuoteHistory::Mixin

    table :booking_payments

    default_primary_key id : UUID, autogenerated: true

    enum PaymentStatus
      PENDING
      AUTHORIZED
      CAPTURED
      FAILED
      REFUNDED
      VOIDED
    end

    enum PaymentMethod
      UNKNOWN
      CASH
      CARD
      BANK_TRANSFER
      ONLINE
    end

    attribute quote_id : UUID
    belongs_to :quote, class_name: BookingQuote, foreign_key: quote_id

    attribute booking_id : Int64
    belongs_to :booking, class_name: Booking, foreign_key: booking_id

    attribute amount_cents : Int32
    attribute currency : String = "AUD"

    attribute status : PaymentStatus = PaymentStatus::PENDING, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::BookingPayment::PaymentStatus)
    attribute payment_method : PaymentMethod = PaymentMethod::UNKNOWN, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::BookingPayment::PaymentMethod)

    attribute provider : String?
    attribute reference : String?
    attribute paid_at : Time?, converter: Time::EpochConverterOptional

    attribute metadata : JSON::Any = JSON::Any.new({} of String => JSON::Any)

    validates :quote_id, presence: true
    validates :booking_id, presence: true

    validate ->(this : BookingPayment) do
      if this.amount_cents < 0
        this.validation_error(:amount_cents, "must be greater than or equal to 0")
      end
    end

    protected def booking_quote_history_quote_id : UUID
      quote_id
    end

    protected def booking_quote_history_changed_fields : Array(String)
      captured_changed_fields.map { |field| "payment.#{field}" }
    end
  end
end
