require "uuid"
require "uuid/json"

require "../base/model"
require "./rate_card"
require "./rate_card_history"

module PlaceOS::Model
  class DurationBand < ::PgORM::Base
    include PgORM::Timestamps
    include RateCardHistory::Mixin

    table :duration_bands

    default_primary_key id : UUID, autogenerated: true

    attribute rate_card_id : UUID
    belongs_to :rate_card, class_name: RateCard, foreign_key: rate_card_id

    attribute name : String
    attribute description : String = ""

    attribute min_minutes : Int32
    attribute max_minutes : Int32?

    attribute priority : Int32 = 100
    attribute active : Bool = true
    attribute metadata : JSON::Any = JSON::Any.new({} of String => JSON::Any)

    validates :rate_card_id, presence: true
    validates :name, presence: true

    validate ->(this : DurationBand) do
      if this.min_minutes < 0
        this.validation_error(:min_minutes, "must be greater than or equal to 0")
      end

      max = this.max_minutes
      if max && max < this.min_minutes
        this.validation_error(:max_minutes, "must be greater than or equal to min_minutes")
      end
    end

    protected def rate_card_history_rate_card_id : UUID
      rate_card_id
    end

    protected def rate_card_history_changed_fields : Array(String)
      captured_changed_fields.map { |field| "duration_band.#{field}" }
    end
  end
end
