require "uuid"
require "uuid/json"

require "../base/model"
require "./rate_card"
require "./rate_card_history"
require "./duration_band"

module PlaceOS::Model
  class PricingRule < ::PgORM::Base
    include PgORM::Timestamps
    include RateCardHistory::Mixin

    table :pricing_rules

    default_primary_key id : UUID, autogenerated: true

    enum CustomerType
      INTERNAL
      EXTERNAL
      STUDENT
      PARTNER
    end

    enum DayType
      WEEKDAY
      WEEKEND
      PUBLIC_HOLIDAY
    end

    enum ChargeBasis
      FIXED
      PER_BOOKING
      PER_HALF_DAY
      PER_FULL_DAY
      PER_HOUR
      PER_ATTENDEE
      PERCENTAGE
    end

    enum ChargeCategory
      VENUE_HIRE
      ASSET_HIRE
      SURCHARGE
      DISCOUNT
      OTHER
    end

    attribute rate_card_id : UUID
    belongs_to :rate_card, class_name: RateCard, foreign_key: rate_card_id

    attribute duration_band_id : UUID?
    belongs_to :duration_band, class_name: DurationBand, foreign_key: duration_band_id

    attribute name : String
    attribute description : String = ""

    attribute charge_category : ChargeCategory, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::PricingRule::ChargeCategory)
    attribute charge_basis : ChargeBasis, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::PricingRule::ChargeBasis)

    attribute amount_cents : Int32

    attribute customer_type : String?
    attribute day_type : String?

    attribute min_attendees : Int32?
    attribute max_attendees : Int32?

    attribute priority : Int32 = 100
    attribute stackable : Bool = false
    attribute active : Bool = true
    attribute metadata : JSON::Any = JSON::Any.new({} of String => JSON::Any)

    validates :rate_card_id, presence: true
    validates :name, presence: true

    validate ->(this : PricingRule) do
      min = this.min_attendees
      max = this.max_attendees

      if min && min < 0
        this.validation_error(:min_attendees, "must be greater than or equal to 0")
      end

      if max && max < 0
        this.validation_error(:max_attendees, "must be greater than or equal to 0")
      end

      if min && max && max < min
        this.validation_error(:max_attendees, "must be greater than or equal to min_attendees")
      end
    end

    protected def rate_card_history_rate_card_id : UUID
      rate_card_id
    end

    protected def rate_card_history_changed_fields : Array(String)
      captured_changed_fields.map { |field| "pricing_rule.#{field}" }
    end
  end
end
