require "uuid"
require "uuid/json"

require "../asset"
require "../asset_type"
require "../base/model"
require "../control_system"
require "../zone"
require "./rate_card"
require "./rate_card_history"

module PlaceOS::Model
  class RateCardAssignment < ::PgORM::Base
    include PgORM::Timestamps
    include RateCardHistory::Mixin

    table :rate_card_assignments

    default_primary_key id : UUID, autogenerated: true

    attribute rate_card_id : UUID
    belongs_to :rate_card, class_name: RateCard, foreign_key: rate_card_id

    attribute asset_type_id : String?
    belongs_to :asset_type, class_name: AssetType, foreign_key: asset_type_id

    attribute asset_id : String?
    belongs_to :asset, class_name: Asset, foreign_key: asset_id

    attribute space_id : String?
    belongs_to :space, class_name: ControlSystem, foreign_key: space_id

    attribute site_id : String?
    belongs_to :site, class_name: Zone, foreign_key: site_id

    validates :rate_card_id, presence: true

    validate ->(this : RateCardAssignment) do
      target_count = 0
      target_count += 1 if this.asset_type_id.presence
      target_count += 1 if this.asset_id.presence
      target_count += 1 if this.space_id.presence
      target_count += 1 if this.site_id.presence

      if target_count != 1
        this.validation_error(:rate_card_id, "requires exactly one target assignment")
      end
    end

    protected def rate_card_history_rate_card_id : UUID
      rate_card_id
    end

    protected def rate_card_history_changed_fields : Array(String)
      captured_changed_fields.map { |field| "rate_card_assignment.#{field}" }
    end
  end
end
