require "uuid"
require "uuid/json"

require "../base/model"
require "../user"

module PlaceOS::Model
  class RateCardHistory < ::PgORM::Base
    table :rate_card_history

    default_primary_key id : UUID, autogenerated: true

    attribute rate_card_id : UUID
    attribute user_id : String?
    attribute email : String
    attribute action : String
    attribute changed_fields : Array(String) = [] of String
    attribute created_at : Time = -> { Time.utc }

    validates :rate_card_id, presence: true
    validates :email, presence: true
    validates :action, presence: true

    before_create do
      self.created_at = Time.utc
    end

    def user_deleted? : Bool
      user_id.nil?
    end

    def self.for_rate_card(rate_card_id : UUID) : Array(self)
      find_all_by_sql(
        "SELECT * FROM rate_card_history WHERE rate_card_id = $1 ORDER BY created_at ASC",
        rate_card_id
      )
    end
  end

  module RateCardHistory::Mixin
    macro included
      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property acting_user : ::PlaceOS::Model::User?

      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property? was_new_record : Bool = false

      @[JSON::Field(ignore: true)]
      @[YAML::Field(ignore: true)]
      property captured_changed_fields : Array(String) = [] of String

      before_save :capture_rate_card_history_state
      after_save :record_rate_card_history_save
      after_destroy :record_rate_card_history_destroy

      protected def capture_rate_card_history_state
        self.was_new_record = new_record?
        self.captured_changed_fields = was_new_record? ? attributes.keys.map(&.to_s) : changed_attributes.keys.map(&.to_s)
      end

      protected def record_rate_card_history_save
        user = acting_user
        return unless user
        action = was_new_record? ? "create" : "update"
        fields = rate_card_history_changed_fields
        return if action == "update" && fields.empty?

        ::PlaceOS::Model::RateCardHistory.create!(
          rate_card_id: rate_card_history_rate_card_id,
          user_id: user.id,
          email: user.email.to_s,
          action: action,
          changed_fields: fields,
        )
      end

      protected def record_rate_card_history_destroy
        user = acting_user
        return unless user

        ::PlaceOS::Model::RateCardHistory.create!(
          rate_card_id: rate_card_history_rate_card_id,
          user_id: user.id,
          email: user.email.to_s,
          action: "delete",
          changed_fields: [] of String,
        )
      end

      protected def rate_card_history_changed_fields : Array(String)
        captured_changed_fields
      end
    end

    abstract def rate_card_history_rate_card_id : UUID
  end
end
