require "uuid"
require "uuid/json"

require "../base/model"
require "./rate_card_history"

module PlaceOS::Model
  class RateCard < ::PgORM::Base
    include PgORM::Timestamps
    include RateCardHistory::Mixin

    table :rate_cards

    default_primary_key id : UUID, autogenerated: true

    enum Kind
      BASE
      ADJUSTMENT
    end

    attribute name : String
    attribute description : String = ""
    attribute kind : Kind = Kind::BASE, converter: PlaceOS::Model::PGEnumConverter(PlaceOS::Model::RateCard::Kind)
    attribute priority : Int32 = 100

    attribute valid_from : Time?, converter: Time::EpochConverterOptional
    attribute valid_to : Time?, converter: Time::EpochConverterOptional

    attribute currency : String = "AUD"
    attribute active : Bool = true
    attribute metadata : JSON::Any = JSON::Any.new({} of String => JSON::Any)

    validates :name, presence: true

    validate ->(this : RateCard) do
      from = this.valid_from
      to = this.valid_to
      if from && to && to < from
        this.validation_error(:valid_to, "must be greater than or equal to valid_from")
      end
    end

    def self.select_base_card(space_id : String? = nil, site_id : String? = nil, at_time : Time = Time.utc) : self?
      find_all_by_sql(<<-SQL, space_id, site_id, at_time, at_time).first?
        WITH RECURSIVE site_chain(id, depth) AS (
          SELECT $2::TEXT AS id, 0 AS depth
          WHERE $2 IS NOT NULL

          UNION ALL

          SELECT z.parent_id, sc.depth + 1
          FROM zone z
                 INNER JOIN site_chain sc ON z.id = sc.id
          WHERE z.parent_id IS NOT NULL
            AND z.parent_id <> ''
        ),
        candidate_cards AS (
          SELECT rc.id AS rate_card_id,
                 MIN(
                   CASE
                     WHEN $1::TEXT IS NOT NULL AND rca.space_id = $1::TEXT THEN 0
                     WHEN sc.id IS NOT NULL THEN sc.depth + 1
                     ELSE 2147483647
                   END
                 ) AS scope_rank
          FROM rate_cards rc
                 INNER JOIN rate_card_assignments rca ON rca.rate_card_id = rc.id
                 LEFT JOIN site_chain sc ON sc.id = rca.site_id
          WHERE rc.active = TRUE
            AND rc.kind = 'BASE'
            AND (
              rca.space_id = $1::TEXT
              OR sc.id IS NOT NULL
            )
            AND (rc.valid_from IS NULL OR rc.valid_from <= $3)
            AND (rc.valid_to IS NULL OR rc.valid_to >= $4)
          GROUP BY rc.id
        )
        SELECT rc.*
        FROM rate_cards rc
               INNER JOIN candidate_cards cc ON cc.rate_card_id = rc.id
        ORDER BY
          cc.scope_rank ASC,
          CASE
            WHEN rc.valid_from IS NOT NULL AND rc.valid_to IS NOT NULL
              THEN EXTRACT(EPOCH FROM (rc.valid_to - rc.valid_from))
            WHEN rc.valid_from IS NOT NULL OR rc.valid_to IS NOT NULL
              THEN 3155760000
            ELSE 3155760001
          END ASC,
          rc.valid_from DESC NULLS LAST,
          rc.priority ASC,
          rc.created_at DESC
        LIMIT 1
      SQL
    end

    def self.select_adjustments(space_id : String? = nil, site_id : String? = nil, at_time : Time = Time.utc) : Array(self)
      find_all_by_sql(<<-SQL, space_id, site_id, at_time, at_time)
        WITH RECURSIVE site_chain(id, depth) AS (
          SELECT $2::TEXT AS id, 0 AS depth
          WHERE $2 IS NOT NULL

          UNION ALL

          SELECT z.parent_id, sc.depth + 1
          FROM zone z
                 INNER JOIN site_chain sc ON z.id = sc.id
          WHERE z.parent_id IS NOT NULL
            AND z.parent_id <> ''
        ),
        candidate_cards AS (
          SELECT rc.id AS rate_card_id,
                 MIN(
                   CASE
                     WHEN $1::TEXT IS NOT NULL AND rca.space_id = $1::TEXT THEN 0
                     WHEN sc.id IS NOT NULL THEN sc.depth + 1
                     ELSE 2147483647
                   END
                 ) AS scope_rank
          FROM rate_cards rc
                 INNER JOIN rate_card_assignments rca ON rca.rate_card_id = rc.id
                 LEFT JOIN site_chain sc ON sc.id = rca.site_id
          WHERE rc.active = TRUE
            AND rc.kind = 'ADJUSTMENT'
            AND (
              rca.space_id = $1::TEXT
              OR sc.id IS NOT NULL
            )
            AND (rc.valid_from IS NULL OR rc.valid_from <= $3)
            AND (rc.valid_to IS NULL OR rc.valid_to >= $4)
          GROUP BY rc.id
        )
        SELECT rc.*
        FROM rate_cards rc
               INNER JOIN candidate_cards cc ON cc.rate_card_id = rc.id
        ORDER BY
          cc.scope_rank ASC,
          rc.priority ASC,
          rc.valid_from DESC NULLS LAST,
          rc.created_at DESC
      SQL
    end

    protected def rate_card_history_rate_card_id : UUID
      id.not_nil!
    end
  end
end
